import { cx } from '../../components/ui/utils.js';
import { useRef, useState } from 'react';
import { useQueries, useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { sileo } from 'sileo';
import { BookOpenCheck, CalendarClock, Check, ChevronLeft, ChevronRight, CircleDot, FilePenLine, Layers3, Pencil, Plus, Search, ShieldCheck, Trash2, UsersRound } from 'lucide-react';
import { apiAllRows, apiJson } from '../../lib/api.js';
import { Button, Input, Select, Textarea, Badge } from '../../components/ui/index.js';
import { Field, QueryState, WorkflowModal, WorkflowStepper, useAllRows, type Scope, type ModuleSearch } from '../shared.js';
import type { Named, Course, Rule, Matrix } from './matrixTypes.js';
import { emptyRule, localDateTime, formatDateTime, draftSnapshot, versionRules } from './matrixUtils.js';

const matrixRuleEffectClasses = {
  "require": "text-[#285c70] bg-[#e1eef2]",
  "waive": "text-[#495a53] bg-[#e9ece9]",
};

const matrixDraftRuleIconClasses = {
  "require": "text-[#285c70] bg-[#e1eef2]",
  "waive": "text-[#495a53] bg-[#e9ece9]",
};
export function Matrices({ scope, search, setSearch }: { scope: Scope; search: ModuleSearch; setSearch: (patch: Partial<ModuleSearch>) => void }) {
  const root = `v1/companies/${scope.companyId}/branches/${scope.branchId}`;
  const qc = useQueryClient();
  const matrices = useAllRows<Named>('training-matrices', `${root}/training-matrices`);
  const matrixId = matrices.data?.rows[0]?.id;
  const detail = useQuery({ queryKey: ['training-matrix-detail', root, matrixId], enabled: Boolean(matrixId), queryFn: () => apiJson<Matrix>(`${root}/training-matrices/${matrixId}`) });
  const courses = useAllRows<Course>('matrix-course-options', `${root}/training-courses`);
  const departments = useAllRows<Named>('matrix-departments', `${root}/departments`);
  const jobs = useAllRows<Named>('matrix-jobs', `${root}/job-functions`);
  const activities = useAllRows<Named>('matrix-activities', `${root}/training-activities`);
  const people = useAllRows<{ id: string; fullName: string }>('matrix-people', `${root}/people`);
  const [step, setStep] = useState(1);
  const [showRuleEditor, setShowRuleEditor] = useState(true);
  const [name, setName] = useState('Matriz de treinamentos');
  const [effectiveFrom, setEffectiveFrom] = useState(localDateTime());
  const [rules, setRules] = useState<Rule[]>([]);
  const [rule, setRule] = useState<Rule>({ ...emptyRule });
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [linkingIndex, setLinkingIndex] = useState<number | null>(null);
  const [courseSearch, setCourseSearch] = useState('');
  const initialSnapshotRef = useRef('');
  const initialRuleSnapshotRef = useRef(JSON.stringify(emptyRule));
  const sectors = useAllRows<Named>('matrix-sectors', `${root}/departments/${rule.departmentId || '0'}/sectors`, Boolean(rule.departmentId));
  const current = detail.data?.versions.find((version) => version.status === 'draft') ?? detail.data?.versions.at(-1);
  const sectorDepartmentIds = [...new Set([...versionRules(current), ...rules].map((item) => item.departmentId).filter((id): id is string => Boolean(id)))];
  const sectorQueries = useQueries({ queries: sectorDepartmentIds.map((departmentId) => ({ queryKey: ['matrix-scope-sectors', root, departmentId], queryFn: () => apiAllRows<Named>(`${root}/departments/${departmentId}/sectors`) })) });
  const sectorNames = new Map(sectorQueries.flatMap((query) => query.data ?? []).map((sector) => [sector.id, sector.name]));
  const save = useMutation({ mutationFn: (_next: number) => apiJson(`${root}/training-matrix/draft`, { method: 'put', json: {
    name: name.trim(), effectiveFrom: new Date(effectiveFrom).toISOString(), rules: rules.map((item) => Object.fromEntries(Object.entries(item).filter(([, value]) => value !== null && value !== undefined && value !== ''))),
  } }), onSuccess: async (_data, next) => { initialSnapshotRef.current = draftSnapshot(name.trim(), effectiveFrom, rules); await qc.invalidateQueries({ queryKey: ['training-matrix-detail'] }); await qc.invalidateQueries({ queryKey: ['training-matrices'] }); setStep(next); }, onError: (error: Error) => sileo.error({ title: 'Não foi possível salvar o rascunho', description: error.message }) });
  const publish = useMutation({ mutationFn: () => apiJson(`${root}/training-matrix/draft/publish`, { method: 'post' }), onSuccess: async () => {
    await qc.invalidateQueries(); setSearch({ action: undefined }); setStep(1); sileo.success({ title: 'Versão da matriz publicada' });
  }, onError: (error: Error) => sileo.error({ title: 'Não foi possível publicar', description: error.message }) });
  const begin = () => {
    const nextRules = versionRules(current);
    const nextName = detail.data?.name ?? 'Matriz de treinamentos';
    const nextEffectiveFrom = current?.status === 'draft' ? localDateTime(new Date(current.effectiveFrom)) : localDateTime(new Date(Math.max(Date.now(), current ? Date.parse(current.effectiveFrom) + 60000 : 0)));
    setRules(nextRules); setName(nextName); setEffectiveFrom(nextEffectiveFrom); initialSnapshotRef.current = draftSnapshot(nextName.trim(), nextEffectiveFrom, nextRules); initialRuleSnapshotRef.current = JSON.stringify(emptyRule);
    setStep(1); setShowRuleEditor(true); setRule({ ...emptyRule }); setEditingIndex(null); setLinkingIndex(null); setSearch({ action: 'new' });
  };
  const scopeLabel = (item: Rule) => [
    item.departmentId && departments.data?.rows.find((row) => row.id === item.departmentId)?.name,
    item.sectorId && (sectorNames.get(item.sectorId) ?? 'Setor não encontrado'), item.jobFunctionId && jobs.data?.rows.find((row) => row.id === item.jobFunctionId)?.name,
    item.personId && people.data?.rows.find((row) => row.id === item.personId)?.fullName,
    item.activityId && activities.data?.rows.find((row) => row.id === item.activityId)?.name,
  ].filter(Boolean).join(' · ') || 'Todos da filial';
  const displayed = versionRules(current).filter((item) => !search.q || item.name.toLocaleLowerCase().includes(search.q.toLocaleLowerCase()));
  const displayedCourseCount = displayed.reduce((sum, item) => sum + item.courseIds.length, 0);
  const uniqueCourseCount = new Set(versionRules(current).flatMap((item) => item.courseIds)).size;
  const closeEditor = () => {
    const dirty = initialSnapshotRef.current !== draftSnapshot(name.trim(), effectiveFrom, rules) || initialRuleSnapshotRef.current !== JSON.stringify(rule);
    if (dirty && !window.confirm('Descartar as alterações ainda não salvas?')) return;
    setSearch({ action: undefined });
  };
  const targetSelect = (label: string, key: 'jobFunctionId' | 'activityId' | 'personId', options: Named[]) => <Field label={label}><Select aria-label={label} value={rule[key] ?? ''} onChange={(event) => setRule({ ...rule, [key]: event.target.value || undefined })}><option value="">Todos</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>;
  const editorFooter = step === 1 ? <><span className={"workflow-modal__progress text-muted text-[0.78rem] font-[720] max-[640px]:hidden"}>Etapa 1 de 4</span><Button type="submit" form="matrix-version-form" loading={save.isPending} trailingIcon={<ChevronRight size={17} />}>Salvar e configurar regras</Button></>
    : step === 2 ? <><Button variant="ghost" onClick={() => setStep(1)} leadingIcon={<ChevronLeft size={17} />}>Voltar</Button><div className={"workflow-modal__footer-end flex gap-[0.55rem] ml-auto max-[640px]:grid max-[640px]:w-full max-[640px]:m-0 max-[640px]:[&_.ui-button]:w-full"}><Button variant="secondary" loading={save.isPending} onClick={() => save.mutate(2)}>Salvar rascunho</Button><Button disabled={!rules.length || rules.some((item) => !item.courseIds.length) || save.isPending} onClick={() => save.mutate(3)} trailingIcon={<ChevronRight size={17} />}>Revisar matriz</Button></div></>
    : step === 3 ? <><Button variant="ghost" onClick={() => setStep(2)} leadingIcon={<ChevronLeft size={17} />}>Voltar às regras</Button><Button onClick={() => setStep(4)} trailingIcon={<ChevronRight size={17} />}>Continuar para publicação</Button></>
    : <><Button variant="ghost" onClick={() => setStep(3)} leadingIcon={<ChevronLeft size={17} />}>Voltar à revisão</Button><Button loading={publish.isPending} onClick={() => publish.mutate()} leadingIcon={<ShieldCheck size={17} />}>Publicar matriz</Button></>;
  return <div className={"[&_.table-scroll]:relative [&_.workflow-stepper_small]:max-w-full [&_.workflow-stepper_small]:whitespace-normal [&_.workflow-stepper_small]:text-center [&_.workflow-stepper_small]:wrap-anywhere [&_.form-stack_input[type='checkbox']]:flex-[0_0_1.15rem] [&_.form-stack_input[type='checkbox']]:w-[1.15rem] [&_.form-stack_input[type='checkbox']]:h-[1.15rem] [&_.form-stack_input[type='checkbox']]:min-h-0 [&_.form-stack_input[type='checkbox']]:p-0 [&_.form-stack_input[type='checkbox']]:m-0 [&_.form-stack_input[type='checkbox']]:accent-accent [&_.training-checkbox]:flex [&_.training-checkbox]:items-center [&_.training-checkbox]:gap-[.65rem] [&_.training-checkbox]:min-h-11 [&_.training-checkbox]:cursor-pointer block"}><section className={"resource-main min-w-0 border border-solid border-line rounded-panel bg-surface shadow-panel max-[520px]:p-[0.85rem] p-0 overflow-hidden"}>
    <div className={"flex items-center justify-between gap-4 p-[1rem_1.25rem] border-b border-solid border-b-line bg-[#fbfbf7] max-[640px]:items-stretch max-[640px]:flex-col max-[640px]:[&_.ui-button]:w-full"}><label className={"search-field flex items-center gap-2 min-w-52 p-[0.55rem_0.7rem] border border-solid border-line rounded-control [&_input]:w-full [&_input]:border-0 [&_input]:[outline:0] [&_input]:bg-transparent max-[800px]:w-full w-[min(22rem,100%)] bg-surface [&_.ui-control]:min-h-auto [&_.ui-control]:p-0 [&_.ui-control]:border-0 [&_.ui-control]:[outline:0] [&_.ui-control]:bg-transparent [&_.ui-control:focus]:[outline:0] focus-within:border-accent focus-within:[outline:3px_solid_var(--color-control-focus)] focus-within:outline-offset-0"}><Search size={18} /><span className={"sr-only absolute w-px h-px p-0 -m-px overflow-hidden [clip:rect(0,0,0,0)] whitespace-nowrap border-0"}>Buscar regra</span><Input value={search.q} onChange={(event) => setSearch({ q: event.target.value })} placeholder="Buscar por regra" /></label><Button onClick={begin} leadingIcon={<Plus size={17} />}>{current?.status === 'draft' ? 'Continuar rascunho' : matrixId ? 'Nova versão' : 'Criar matriz'}</Button></div>
    <QueryState loading={matrices.isLoading || detail.isLoading} error={matrices.isError || detail.isError}>
      {current && <header className={"flex items-center justify-between gap-8 p-[1.6rem_1.75rem] text-[#f6fbf8] bg-[#17372d] [&_h2]:m-0 [&_h2]:text-white [&_h2]:text-[1.2rem] [&_p]:m-[0.3rem_0_0] [&_p]:text-[#bad0c7] [&_p]:text-[0.8rem] max-[900px]:items-start max-[900px]:flex-col max-[640px]:px-4"}><div className={"flex items-center gap-[0.9rem] min-w-0 max-[640px]:items-start"}><span className={"grid flex-[0_0_auto] place-items-center w-[2.8rem] h-[2.8rem] rounded-[0.75rem] text-[#17372d] bg-[#d8ecdf]"}><Layers3 size={22} /></span><div><div className={"flex items-center gap-[0.65rem] max-[640px]:items-start max-[640px]:flex-col"}><h2>{detail.data?.name}</h2><Badge tone={current.status === 'draft' ? 'warning' : 'success'}>{current.status === 'draft' ? 'Rascunho' : 'Publicada'}</Badge></div><p>Versão {current.versionNo} · Vigência em {formatDateTime(current.effectiveFrom)}</p></div></div><dl className={"grid grid-cols-[repeat(3,auto)] gap-0 m-0 [&_div]:min-w-22 [&_div]:p-[0_1.1rem] [&_div]:border-l [&_div]:border-solid [&_div]:border-l-[rgb(255_255_255/14%)] [&_dt]:text-[#acc5bb] [&_dt]:text-[0.68rem] [&_dt]:font-[750] [&_dd]:m-[0.2rem_0_0] [&_dd]:text-white [&_dd]:text-[1.2rem] [&_dd]:font-[820] [&_dd]:tabular-nums max-[900px]:w-full max-[900px]:[&_div]:flex-1 max-[900px]:[&_div]:px-[0.8rem] max-[900px]:[&_div:first-child]:pl-0 max-[900px]:[&_div:first-child]:border-l-0 max-[640px]:grid-cols-3 max-[640px]:[&_div]:min-w-0 max-[640px]:[&_dt]:text-[0.875rem]"}><div><dt>Regras</dt><dd>{versionRules(current).length}</dd></div><div><dt>Cursos únicos</dt><dd>{uniqueCourseCount}</dd></div><div><dt>Vínculos</dt><dd>{versionRules(current).reduce((sum, item) => sum + item.courseIds.length, 0)}</dd></div></dl></header>}
      {current && <div className={"flex items-end justify-between gap-4 p-[1.45rem_1.75rem_0.9rem] [&_h3]:m-0 [&_h3]:text-[1rem] [&_p]:m-[0.25rem_0_0] [&_p]:text-muted [&_p]:text-[0.78rem] max-[640px]:px-4"}><div><h3>Regras da matriz</h3><p>{search.q ? `${displayed.length} regras encontradas · ${displayedCourseCount} vínculos` : 'Quem precisa de cada treinamento e em qual condição.'}</p></div></div>}
      <div className={"grid p-[0_1.75rem_1.2rem] max-[640px]:px-4"}>{displayed.map((item, index) => <article className={"grid grid-cols-[auto_minmax(0,1fr)_auto] items-start gap-[0.9rem] p-[1.15rem_0] border-t border-solid border-t-line first:border-t-0 max-[640px]:grid-cols-[auto_minmax(0,1fr)]"} key={`${item.name}-${index}`}><div className={cx("grid place-items-center w-[2.55rem] h-[2.55rem] rounded-[0.7rem]", matrixRuleEffectClasses[item.effect])} aria-hidden="true">{item.effect === 'require' ? <BookOpenCheck size={21} /> : <ShieldCheck size={21} />}</div><div className={"matrix-rule__content min-w-0"}><div className={"flex items-start justify-between gap-4 [&_h3]:m-0 [&_h3]:text-[0.95rem] [&_p]:flex [&_p]:items-center [&_p]:gap-[0.35rem] [&_p]:m-[0.3rem_0_0] [&_p]:text-muted [&_p]:text-[0.76rem] max-[640px]:flex-col max-[640px]:[&_p]:text-[0.875rem]"}><div><h3>{item.name}</h3><p><UsersRound size={15} />{scopeLabel(item)}</p></div><Badge tone={item.effect === 'require' ? 'info' : 'neutral'}>{item.effect === 'require' ? 'Treinamento exigido' : 'Dispensa'}</Badge></div><div className={"grid grid-cols-[7.6rem_minmax(0,1fr)] gap-[0.8rem] mt-[0.8rem] [&_>_span]:text-muted [&_>_span]:text-[0.7rem] [&_>_span]:font-[760] [&_ul]:flex [&_ul]:flex-wrap [&_ul]:gap-[0.35rem] [&_ul]:m-0 [&_ul]:p-0 [&_ul]:list-none [&_li]:p-[0.25rem_0.45rem] [&_li]:rounded-[0.45rem] [&_li]:text-[#2d4c41] [&_li]:bg-[#edf3ef] [&_li]:text-[0.72rem] [&_li]:font-[680] [&_p]:m-0 [&_p]:text-muted [&_p]:text-[0.75rem] max-[640px]:grid-cols-[1fr] max-[640px]:gap-[0.4rem] max-[640px]:[&_>_span]:text-[0.875rem] max-[640px]:[&_li]:text-[0.875rem]"}><span>Cursos vinculados</span>{item.courseIds.length ? <ul>{item.courseIds.map((id) => <li key={id}>{courses.data?.rows.find((course) => course.id === id)?.name ?? `Curso ${id}`}</li>)}</ul> : <p>Nenhum curso vinculado.</p>}</div></div><span className={"grid min-w-[3.4rem] justify-items-end text-ink text-[1.1rem] font-[820] tabular-nums [&_small]:text-muted [&_small]:text-[0.66rem] [&_small]:font-[650] max-[640px]:hidden max-[640px]:[&_small]:text-[0.875rem]"}>{item.courseIds.length}<small>{item.courseIds.length === 1 ? 'curso' : 'cursos'}</small></span></article>)}</div>
      {!current && <div className={"grid justify-items-center p-[4rem_1.5rem] text-muted text-center [&_svg]:text-accent [&_h3]:m-[0.8rem_0_0.35rem] [&_h3]:text-ink [&_p]:max-w-[42ch] [&_p]:m-[0_0_1.1rem] [&_p]:leading-normal"}><Layers3 size={30} /><h3>Sua matriz começa pelas regras</h3><p>Crie a primeira versão para relacionar públicos e treinamentos obrigatórios.</p><Button onClick={begin} leadingIcon={<Plus size={17} />}>Criar matriz</Button></div>}
      {current && !displayed.length && <div className={"grid justify-items-center p-[4rem_1.5rem] text-muted text-center [&_svg]:text-accent [&_h3]:m-[0.8rem_0_0.35rem] [&_h3]:text-ink [&_p]:max-w-[42ch] [&_p]:m-[0_0_1.1rem] [&_p]:leading-normal"}><Search size={28} /><h3>Nenhuma regra encontrada</h3><p>Tente outro termo ou limpe a busca para visualizar toda a matriz.</p><Button variant="secondary" onClick={() => setSearch({ q: '' })}>Limpar busca</Button></div>}
    </QueryState>
  </section>{search.action === 'new' && <WorkflowModal title={current?.status === 'draft' ? 'Editar rascunho da matriz' : matrixId ? 'Criar nova versão' : 'Criar matriz'} description="Monte a versão com calma. Somente a publicação passa a gerar obrigações." focusKey={step} onClose={closeEditor} footer={editorFooter}>
    <WorkflowStepper steps={['Versão', 'Regras', 'Revisão', 'Publicação']} current={step} onStep={setStep} />
    {step === 1 && <section className={"w-[min(52rem,100%)] m-[0_auto] grid grid-cols-[minmax(14rem,0.7fr)_minmax(20rem,1.3fr)] gap-10 pt-8 max-[640px]:grid-cols-[1fr] max-[640px]:gap-4 max-[640px]:pt-0"}><div className={"flex items-start gap-[0.8rem] [&_>_span]:grid [&_>_span]:flex-[0_0_auto] [&_>_span]:place-items-center [&_>_span]:w-[2.6rem] [&_>_span]:h-[2.6rem] [&_>_span]:rounded-[0.7rem] [&_>_span]:text-accent-strong [&_>_span]:bg-accent-soft [&_h3]:m-0 [&_p]:m-[0.35rem_0_0] [&_p]:text-muted [&_p]:text-[0.8rem] [&_p]:leading-normal max-[640px]:[&_p]:text-[0.875rem]"}><span><CalendarClock size={21} /></span><div><h3>Dados da versão</h3><p>Defina como esta matriz será identificada e quando suas regras entram em vigor.</p></div></div><form id="matrix-version-form" className={"grid gap-[0.8rem] [&_label]:grid [&_label]:gap-[0.4rem] [&_label]:text-muted [&_label]:text-[0.78rem] [&_label]:font-[750] [&_input:not([type='checkbox']):not([type='hidden'])]:w-full [&_input:not([type='checkbox']):not([type='hidden'])]:min-h-11 [&_input:not([type='checkbox']):not([type='hidden'])]:p-[0.65rem_0.75rem] [&_input:not([type='checkbox']):not([type='hidden'])]:border [&_input:not([type='checkbox']):not([type='hidden'])]:border-solid [&_input:not([type='checkbox']):not([type='hidden'])]:border-control-border [&_input:not([type='checkbox']):not([type='hidden'])]:rounded-control [&_input:not([type='checkbox']):not([type='hidden'])]:text-ink [&_input:not([type='checkbox']):not([type='hidden'])]:bg-white [&_input[aria-invalid='true']]:border-danger [&_.ui-checkbox-field]:flex [&_.ui-checkbox-field]:items-center [&_.ui-checkbox-field]:justify-between [&_.ui-checkbox-field]:gap-3 [&_.ui-checkbox-field]:w-full [&_.ui-checkbox-field]:min-h-10 [&_.ui-checkbox-field]:text-ink [&_.ui-checkbox-field]:cursor-pointer [align-content:start] p-[1.1rem] border border-solid border-line rounded-panel bg-[#fbfbf7]"} onSubmit={(event) => { event.preventDefault(); save.mutate(2); }}><Field label="Nome da matriz"><Input aria-label="Nome da matriz" required maxLength={180} value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Início da vigência"><Input aria-label="Início da vigência" required type="datetime-local" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} /></Field></form></section>}
    {step === 2 && <div className={"grid grid-cols-[minmax(19rem,0.8fr)_minmax(24rem,1.2fr)] gap-[1.1rem] items-start max-[900px]:grid-cols-[1fr]"}><section className={"min-w-0 p-4 border border-solid border-line rounded-panel bg-[#fafaf6] max-[900px]:p-[0.9rem]"}>{!showRuleEditor && <div className={"grid justify-items-center min-h-80 p-[2rem_1rem] text-muted text-center [&_svg]:text-accent [&_h3]:m-[0.7rem_0_0.3rem] [&_h3]:text-ink [&_p]:max-w-[34ch] [&_p]:m-[0_0_1rem] [&_p]:text-[0.78rem] [&_p]:leading-normal"}><FilePenLine size={26} /><h3>Selecione uma regra para editar</h3><p>Ou comece uma nova regra para definir público, efeito e cursos.</p><Button variant="secondary" onClick={() => { setShowRuleEditor(true); setEditingIndex(null); setRule({ ...emptyRule }); initialRuleSnapshotRef.current = JSON.stringify(emptyRule); setLinkingIndex(null); }} leadingIcon={<Plus size={16} />}>Nova regra</Button></div>}{showRuleEditor && <form className={"grid gap-[0.8rem] [&_label]:grid [&_label]:gap-[0.4rem] [&_label]:text-muted [&_label]:text-[0.78rem] [&_label]:font-[750] [&_input:not([type='checkbox']):not([type='hidden'])]:w-full [&_input:not([type='checkbox']):not([type='hidden'])]:min-h-11 [&_input:not([type='checkbox']):not([type='hidden'])]:p-[0.65rem_0.75rem] [&_input:not([type='checkbox']):not([type='hidden'])]:border [&_input:not([type='checkbox']):not([type='hidden'])]:border-solid [&_input:not([type='checkbox']):not([type='hidden'])]:border-control-border [&_input:not([type='checkbox']):not([type='hidden'])]:rounded-control [&_input:not([type='checkbox']):not([type='hidden'])]:text-ink [&_input:not([type='checkbox']):not([type='hidden'])]:bg-white [&_input[aria-invalid='true']]:border-danger [&_.ui-checkbox-field]:flex [&_.ui-checkbox-field]:items-center [&_.ui-checkbox-field]:justify-between [&_.ui-checkbox-field]:gap-3 [&_.ui-checkbox-field]:w-full [&_.ui-checkbox-field]:min-h-10 [&_.ui-checkbox-field]:text-ink [&_.ui-checkbox-field]:cursor-pointer"} onSubmit={(event) => { event.preventDefault(); if (!rule.name.trim()) return;
      if (editingIndex !== null) { setRules((items) => items.map((item, index) => index === editingIndex ? { ...rule, name: rule.name.trim() } : item)); setLinkingIndex(editingIndex); }
      else { setRules((items) => [...items, { ...rule, name: rule.name.trim() }]); setLinkingIndex(rules.length); }
      setRule({ ...emptyRule }); initialRuleSnapshotRef.current = JSON.stringify(emptyRule); setEditingIndex(null); setShowRuleEditor(false);
    }}><div className={"[&_>_span]:grid [&_>_span]:flex-[0_0_auto] [&_>_span]:place-items-center [&_>_span]:w-9 [&_>_span]:h-9 [&_>_span]:rounded-[0.7rem] [&_>_span]:text-accent-strong [&_>_span]:bg-accent-soft [&_h3]:m-0 [&_p]:m-[0.35rem_0_0] [&_p]:text-muted [&_p]:text-[0.8rem] [&_p]:leading-normal flex items-start gap-[0.7rem] mb-[0.35rem] max-[640px]:[&_p]:text-[0.875rem]"}><span><FilePenLine size={19} /></span><div><h3>{editingIndex === null ? 'Criar regra' : 'Editar regra'}</h3><p>Sem filtros, a regra abrange todos da filial.</p></div></div><Field label="Nome da regra"><Input aria-label="Nome da regra" required maxLength={180} value={rule.name} onChange={(event) => setRule({ ...rule, name: event.target.value })} /></Field>
      <Field label="Efeito"><Select aria-label="Efeito da regra" value={rule.effect} onChange={(event) => setRule({ ...rule, effect: event.target.value as Rule['effect'] })}><option value="require">Exigir treinamento</option><option value="waive">Dispensar treinamento</option></Select></Field>
      <Field label={rule.effect === 'waive' ? 'Motivo da dispensa' : 'Descrição (opcional)'}><Textarea aria-label="Descrição da regra" required={rule.effect === 'waive'} maxLength={500} value={rule.reason ?? ''} onChange={(event) => setRule({ ...rule, reason: event.target.value })} /></Field>
      <div className={"flex items-center gap-[0.6rem] mt-[0.4rem] text-muted text-[0.7rem] font-extrabold [&::after]:flex-1 [&::after]:h-px [&::after]:bg-line [&::after]:[content:'']"}><span>Escopo da regra</span></div>
      <Field label="Departamento"><Select aria-label="Departamento da regra" value={rule.departmentId ?? ''} onChange={(event) => setRule({ ...rule, departmentId: event.target.value || undefined, sectorId: undefined })}><option value="">Todos</option>{departments.data?.rows.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>
      {rule.departmentId && <Field label="Setor"><Select aria-label="Setor da regra" value={rule.sectorId ?? ''} onChange={(event) => setRule({ ...rule, sectorId: event.target.value || undefined })}><option value="">Todos</option>{sectors.data?.rows.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>}
      {targetSelect('Cargo', 'jobFunctionId', jobs.data?.rows ?? [])}{targetSelect('Atividade', 'activityId', activities.data?.rows ?? [])}{targetSelect('Colaborador', 'personId', people.data?.rows.map((p) => ({ id: p.id, name: p.fullName })) ?? [])}
      <Button type="submit" variant="secondary" trailingIcon={<ChevronRight size={16} />}>{editingIndex === null ? 'Criar e vincular cursos' : 'Salvar alterações'}</Button>
    </form>}</section><section className={"min-w-0 p-4 border border-solid border-line rounded-panel bg-white [&_>_header]:flex [&_>_header]:items-start [&_>_header]:justify-between [&_>_header]:gap-3 [&_>_header]:pb-[0.85rem] [&_>_header]:border-b [&_>_header]:border-solid [&_>_header]:border-b-line [&_>_header_h3]:m-0 [&_>_header_h3]:text-[0.92rem] [&_>_header_p]:m-[0.25rem_0_0] [&_>_header_p]:text-muted [&_>_header_p]:text-[0.74rem] max-[900px]:p-[0.9rem] max-[640px]:[&_>_header]:items-stretch max-[640px]:[&_>_header]:flex-col max-[640px]:[&_>_header_p]:text-[0.875rem]"}><header><div><h3>Regras desta versão</h3><p>{rules.length ? `${rules.length} ${rules.length === 1 ? 'regra configurada' : 'regras configuradas'}` : 'Crie a primeira regra para continuar.'}</p></div><Button variant="secondary" size="sm" onClick={() => { setShowRuleEditor(true); setEditingIndex(null); setRule({ ...emptyRule }); initialRuleSnapshotRef.current = JSON.stringify(emptyRule); setLinkingIndex(null); }} leadingIcon={<Plus size={15} />}>Nova regra</Button></header>
    <div className={"grid [&_article]:grid [&_article]:grid-cols-[minmax(0,1fr)_auto] [&_article]:items-center [&_article]:border-b [&_article]:border-solid [&_article]:border-b-[#e8ebe7] [&_article[aria-current='true']]:[margin-inline:-0.45rem] [&_article[aria-current='true']]:px-[0.45rem] [&_article[aria-current='true']]:rounded-compact [&_article[aria-current='true']]:bg-[#f0f5f2]"}>{rules.map((item, index) => <article key={index} aria-current={linkingIndex === index ? 'true' : undefined}><button type="button" className={"grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-[0.6rem] min-w-0 p-[0.75rem_0.35rem] border-0 text-inherit bg-transparent text-left cursor-pointer [&:hover_strong]:text-accent-strong [&_>_span:nth-child(2)]:min-w-0 [&_strong]:block [&_strong]:overflow-hidden [&_strong]:text-ellipsis [&_strong]:whitespace-nowrap [&_strong]:text-[0.8rem] [&_small]:block [&_small]:overflow-hidden [&_small]:text-ellipsis [&_small]:whitespace-nowrap [&_small]:mt-[0.2rem] [&_small]:text-muted [&_small]:text-[0.68rem] max-[640px]:[&_small]:text-[0.875rem]"} onClick={() => setLinkingIndex(index)}><span className={cx("grid place-items-center w-8 h-8 rounded-compact", matrixDraftRuleIconClasses[item.effect])}>{item.effect === 'require' ? <BookOpenCheck size={17} /> : <ShieldCheck size={17} />}</span><span><strong>{item.name}</strong><small>{scopeLabel(item)} · {item.courseIds.length} {item.courseIds.length === 1 ? 'curso' : 'cursos'}</small></span><ChevronRight size={16} /></button><div className={"flex [&_.ui-button--icon]:w-8 [&_.ui-button--icon]:h-8 max-[640px]:[&_.ui-button--icon]:w-11 max-[640px]:[&_.ui-button--icon]:h-11"}><Button variant="ghost" size="icon" aria-label={`Editar ${item.name}`} onClick={() => { setRule({ ...item }); initialRuleSnapshotRef.current = JSON.stringify(item); setEditingIndex(index); setShowRuleEditor(true); setLinkingIndex(null); }}><Pencil size={15} /></Button><Button variant="ghost" size="icon" className={"danger"} aria-label={`Remover ${item.name}`} onClick={() => { setRules((items) => items.filter((_, i) => i !== index)); setLinkingIndex(null); setEditingIndex(null); setRule({ ...emptyRule }); initialRuleSnapshotRef.current = JSON.stringify(emptyRule); }}><Trash2 size={15} /></Button></div></article>)}</div>
    {linkingIndex !== null && rules[linkingIndex] && <fieldset className={"selection-list grid gap-[0.45rem] m-0 overflow-auto border border-solid border-line rounded-control [&_label]:flex [&_label]:gap-[0.65rem] [&_label]:items-center [&_label]:p-[0.55rem] [&_label]:rounded-compact [&_label:hover]:bg-[#f4f5f1] [&_label_span]:grid [&_small]:block [&_small]:text-muted [&_small]:text-[0.72rem] [&_.search-field_.ui-control]:min-h-auto [&_.search-field_.ui-control]:p-0 [&_.search-field_.ui-control]:border-0 [&_.search-field_.ui-control]:[outline:0] [&_.search-field_.ui-control]:bg-transparent [&_.search-field_.ui-control:focus]:[outline:0] [&_.search-field:focus-within]:border-accent [&_.search-field:focus-within]:[outline:3px_solid_var(--color-control-focus)] [&_.search-field:focus-within]:outline-offset-0 max-h-92 mt-[0.9rem] p-[0.9rem] bg-[#fafaf6] [&_legend]:max-w-full [&_legend]:p-[0_0.35rem] [&_legend]:text-[0.82rem] [&_legend]:font-extrabold [&_>_p]:m-[0_0_0.35rem] [&_>_p]:text-muted [&_>_p]:text-[0.72rem] [&_>_p]:leading-[1.45] [&_.search-field]:w-full [&_.search-field]:mb-1 [&_.search-field]:bg-white max-[640px]:[&_>_p]:text-[0.875rem]"}><legend>Cursos para {rules[linkingIndex]!.name}</legend><p>Selecione todos os cursos desta regra. Evidência é sempre obrigatória; a frequência vem do curso.</p><label className={"search-field flex items-center gap-2 min-w-52 p-[0.55rem_0.7rem] border border-solid border-line rounded-control bg-white [&_input]:w-full [&_input]:border-0 [&_input]:[outline:0] [&_input]:bg-transparent max-[800px]:w-full"}><Search size={16} /><span className={"sr-only absolute w-px h-px p-0 -m-px overflow-hidden [clip:rect(0,0,0,0)] whitespace-nowrap border-0"}>Buscar curso</span><Input aria-label="Buscar curso para vincular" placeholder="Buscar curso" value={courseSearch} onChange={(event) => setCourseSearch(event.target.value)} /></label>
      <QueryState loading={courses.isLoading} error={courses.isError}>{courses.data?.rows.filter((course) => course.name.toLocaleLowerCase().includes(courseSearch.toLocaleLowerCase())).map((course) => <label key={course.id}><input type="checkbox" checked={rules[linkingIndex]!.courseIds.includes(course.id)} onChange={(event) => setRules((items) => items.map((item, index) => index !== linkingIndex ? item : { ...item, courseIds: event.target.checked ? [...item.courseIds, course.id] : item.courseIds.filter((id) => id !== course.id) }))} /><span>{course.name}<small>{course.validityDays === null ? 'Sem frequência' : `${course.validityDays} dias`} · Evidência obrigatória</small></span></label>)}</QueryState>
      <Button variant="ghost" onClick={() => setLinkingIndex(null)} leadingIcon={<Check size={16} />}>Concluir seleção</Button></fieldset>}
    {!rules.length && <div className={"grid justify-items-center min-h-80 p-[2rem_1rem] text-muted text-center [&_svg]:text-accent [&_p]:max-w-[34ch] [&_p]:m-[0_0_1rem] [&_p]:text-[0.78rem] [&_p]:leading-normal"}><CircleDot size={22} /><p>As regras criadas aparecerão aqui para você revisar e vincular cursos.</p></div>}
    {rules.some((item) => !item.courseIds.length) && <p className={"m-[0.85rem_0_0] p-[0.65rem_0.75rem] rounded-compact text-[#72520f] bg-[#fbf2d9] text-[0.72rem] font-[690] max-[640px]:text-[0.875rem]"}>Vincule ao menos um curso a cada regra antes de revisar.</p>}</section></div>}
    {step === 3 && <section className={"w-[min(52rem,100%)] m-[0_auto] [&_>_header]:flex [&_>_header]:items-start [&_>_header]:justify-between [&_>_header]:gap-6 [&_>_header]:mb-4 [&_>_header_h3]:m-0 [&_>_header_p]:max-w-[58ch] [&_>_header_p]:m-[0.35rem_0_0] [&_>_header_p]:text-muted [&_>_header_p]:text-[0.8rem] [&_>_header_p]:leading-normal [&_>_header_dl]:flex [&_>_header_dl]:m-0 [&_>_header_dl_div]:min-w-20 [&_>_header_dl_div]:pl-4 [&_>_header_dl_div]:border-l [&_>_header_dl_div]:border-solid [&_>_header_dl_div]:border-l-line [&_dt]:text-muted [&_dt]:text-[0.66rem] [&_dt]:font-[750] [&_dd]:m-[0.15rem_0_0] [&_dd]:text-[1.15rem] [&_dd]:font-[820] [&_dd]:tabular-nums max-[640px]:[&_>_header]:items-stretch max-[640px]:[&_>_header]:flex-col max-[640px]:[&_>_header_p]:text-[0.875rem] max-[640px]:[&_>_header_dl]:w-full"}><header><div><h3>Revise antes de publicar</h3><p>Confira o público e os treinamentos de cada regra. A precedência é aplicada automaticamente.</p></div><dl><div><dt>Regras</dt><dd>{rules.length}</dd></div><div><dt>Vínculos</dt><dd>{rules.reduce((sum, item) => sum + item.courseIds.length, 0)}</dd></div></dl></header><div className={"grid border-t border-solid border-t-line [&_article]:grid [&_article]:grid-cols-[minmax(15rem,0.9fr)_minmax(0,1.1fr)] [&_article]:gap-4 [&_article]:p-[1rem_0] [&_article]:border-b [&_article]:border-solid [&_article]:border-b-line [&_article_>_div]:flex [&_article_>_div]:items-start [&_article_>_div]:gap-[0.7rem] [&_strong]:block [&_strong]:text-[0.85rem] [&_p]:m-[0.25rem_0_0] [&_p]:text-muted [&_p]:text-[0.72rem] [&_ul]:m-0 [&_ul]:pl-[1.1rem] [&_ul]:text-[0.77rem] [&_ul]:leading-[1.6] max-[640px]:[&_article]:grid-cols-[1fr] max-[640px]:[&_article]:gap-4 max-[640px]:[&_article]:pt-0 max-[640px]:[&_p]:text-[0.875rem] max-[640px]:[&_ul]:text-[0.875rem]"}>{rules.map((item, index) => <article key={index}><div><span className={cx("grid place-items-center w-[2.55rem] h-[2.55rem] rounded-[0.7rem]", matrixRuleEffectClasses[item.effect])}>{item.effect === 'require' ? <BookOpenCheck size={19} /> : <ShieldCheck size={19} />}</span><div><strong>{item.name}</strong><p>{scopeLabel(item)} · {item.effect === 'require' ? 'Exigir treinamento' : 'Dispensar treinamento'}</p></div></div><ul>{item.courseIds.map((id) => <li key={id}>{courses.data?.rows.find((course) => course.id === id)?.name ?? id}</li>)}</ul></article>)}</div><p className={"flex items-center gap-[0.55rem] m-[1rem_0_0] p-3 rounded-[0.65rem] text-accent-strong bg-accent-soft text-[0.76rem] font-[690] max-[640px]:text-[0.875rem]"}><ShieldCheck size={18} />Toda realização exige evidência. A versão publicada não poderá ser alterada.</p></section>}
    {step === 4 && <section className={"w-[min(52rem,100%)] m-[0_auto] grid grid-cols-[auto_minmax(0,1fr)] gap-[1.1rem] max-w-152 mt-12 p-6 border border-solid border-[#a9c9ba] rounded-panel bg-[#f1f7f3] [&_h3]:m-0 [&_h3]:text-[1.15rem] [&_p]:m-[0.5rem_0_0] [&_p]:text-muted [&_p]:leading-[1.55] [&_ul]:m-[1rem_0_0] [&_ul]:pl-[1.1rem] [&_ul]:text-[#365048] [&_ul]:text-[0.8rem] [&_ul]:leading-[1.8] max-[640px]:mt-4 max-[640px]:p-4"}><span className={"grid place-items-center w-[3.3rem] h-[3.3rem] rounded-[0.85rem] text-white bg-accent"}><ShieldCheck size={28} /></span><div><h3>Pronto para publicar?</h3><p>Ao confirmar, a versão <strong>{name}</strong> entra em vigor em {formatDateTime(effectiveFrom)} e passa a gerar obrigações.</p><ul><li>{rules.length} {rules.length === 1 ? 'regra configurada' : 'regras configuradas'}</li><li>{rules.reduce((sum, item) => sum + item.courseIds.length, 0)} vínculos com cursos</li><li>Versão imutável após publicação</li></ul></div></section>}
  </WorkflowModal>}</div>;
}
