import { useRef, useState } from 'react';
import { useQueries, useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { sileo } from 'sileo';
import { BookOpenCheck, CalendarClock, Check, ChevronLeft, ChevronRight, CircleDot, FilePenLine, Layers3, Pencil, Plus, Search, ShieldCheck, Trash2, UsersRound } from 'lucide-react';
import { apiAllRows, apiJson } from '../../lib/api.js';
import { Button, Input, Select, Textarea, Badge } from '../../components/ui/index.js';
import { Field, QueryState, WorkflowModal, WorkflowStepper, useAllRows, type Scope, type ModuleSearch } from '../shared.js';
import type { Named, Course, Rule, Matrix } from './matrixTypes.js';
import { emptyRule, localDateTime, formatDateTime, draftSnapshot, versionRules } from './matrixUtils.js';
export function Matrices({ scope, search, setSearch }: { scope: Scope; search: ModuleSearch; setSearch: (patch: Partial<ModuleSearch>) => void }) {
  const root = `v1/companies/${scope.companyId}/branches/${scope.branchId}`;
  const qc = useQueryClient();
  const matrices = useAllRows<Named>('training-matrices', `${root}/training-matrices`);
  const matrixId = matrices.data?.rows[0]?.id;
  const detail = useQuery({ queryKey: ['training-matrix-detail', root, matrixId], enabled: Boolean(matrixId), queryFn: () => apiJson<Matrix>(`${root}/training-matrices/${matrixId}`) });
  const courses = useAllRows<Course>('matrix-course-options', `${root}/training-courses`);
  const departments = useAllRows<Named>('matrix-departments', `${root}/departments`);
  const jobs = useAllRows<Named>('matrix-jobs', `${root}/job-functions`);
  const activities = useAllRows<Named>('matrix-activities', `${root}/training-activities`);
  const people = useAllRows<{ id: string; fullName: string }>('matrix-people', `${root}/people`);
  const [step, setStep] = useState(1);
  const [showRuleEditor, setShowRuleEditor] = useState(true);
  const [name, setName] = useState('Matriz de treinamentos');
  const [effectiveFrom, setEffectiveFrom] = useState(localDateTime());
  const [rules, setRules] = useState<Rule[]>([]);
  const [rule, setRule] = useState<Rule>({ ...emptyRule });
  const [editingIndex, setEditingIndex] = useState<number | null>(null);
  const [linkingIndex, setLinkingIndex] = useState<number | null>(null);
  const [courseSearch, setCourseSearch] = useState('');
  const initialSnapshotRef = useRef('');
  const initialRuleSnapshotRef = useRef(JSON.stringify(emptyRule));
  const sectors = useAllRows<Named>('matrix-sectors', `${root}/departments/${rule.departmentId || '0'}/sectors`, Boolean(rule.departmentId));
  const current = detail.data?.versions.find((version) => version.status === 'draft') ?? detail.data?.versions.at(-1);
  const sectorDepartmentIds = [...new Set([...versionRules(current), ...rules].map((item) => item.departmentId).filter((id): id is string => Boolean(id)))];
  const sectorQueries = useQueries({ queries: sectorDepartmentIds.map((departmentId) => ({ queryKey: ['matrix-scope-sectors', root, departmentId], queryFn: () => apiAllRows<Named>(`${root}/departments/${departmentId}/sectors`) })) });
  const sectorNames = new Map(sectorQueries.flatMap((query) => query.data ?? []).map((sector) => [sector.id, sector.name]));
  const save = useMutation({ mutationFn: (_next: number) => apiJson(`${root}/training-matrix/draft`, { method: 'put', json: {
    name: name.trim(), effectiveFrom: new Date(effectiveFrom).toISOString(), rules: rules.map((item) => Object.fromEntries(Object.entries(item).filter(([, value]) => value !== null && value !== undefined && value !== ''))),
  } }), onSuccess: async (_data, next) => { initialSnapshotRef.current = draftSnapshot(name.trim(), effectiveFrom, rules); await qc.invalidateQueries({ queryKey: ['training-matrix-detail'] }); await qc.invalidateQueries({ queryKey: ['training-matrices'] }); setStep(next); }, onError: (error: Error) => sileo.error({ title: 'Não foi possível salvar o rascunho', description: error.message }) });
  const publish = useMutation({ mutationFn: () => apiJson(`${root}/training-matrix/draft/publish`, { method: 'post' }), onSuccess: async () => {
    await qc.invalidateQueries(); setSearch({ action: undefined }); setStep(1); sileo.success({ title: 'Versão da matriz publicada' });
  }, onError: (error: Error) => sileo.error({ title: 'Não foi possível publicar', description: error.message }) });
  const begin = () => {
    const nextRules = versionRules(current);
    const nextName = detail.data?.name ?? 'Matriz de treinamentos';
    const nextEffectiveFrom = current?.status === 'draft' ? localDateTime(new Date(current.effectiveFrom)) : localDateTime(new Date(Math.max(Date.now(), current ? Date.parse(current.effectiveFrom) + 60000 : 0)));
    setRules(nextRules); setName(nextName); setEffectiveFrom(nextEffectiveFrom); initialSnapshotRef.current = draftSnapshot(nextName.trim(), nextEffectiveFrom, nextRules); initialRuleSnapshotRef.current = JSON.stringify(emptyRule);
    setStep(1); setShowRuleEditor(true); setRule({ ...emptyRule }); setEditingIndex(null); setLinkingIndex(null); setSearch({ action: 'new' });
  };
  const scopeLabel = (item: Rule) => [
    item.departmentId && departments.data?.rows.find((row) => row.id === item.departmentId)?.name,
    item.sectorId && (sectorNames.get(item.sectorId) ?? 'Setor não encontrado'), item.jobFunctionId && jobs.data?.rows.find((row) => row.id === item.jobFunctionId)?.name,
    item.personId && people.data?.rows.find((row) => row.id === item.personId)?.fullName,
    item.activityId && activities.data?.rows.find((row) => row.id === item.activityId)?.name,
  ].filter(Boolean).join(' · ') || 'Todos da filial';
  const displayed = versionRules(current).filter((item) => !search.q || item.name.toLocaleLowerCase().includes(search.q.toLocaleLowerCase()));
  const displayedCourseCount = displayed.reduce((sum, item) => sum + item.courseIds.length, 0);
  const uniqueCourseCount = new Set(versionRules(current).flatMap((item) => item.courseIds)).size;
  const closeEditor = () => {
    const dirty = initialSnapshotRef.current !== draftSnapshot(name.trim(), effectiveFrom, rules) || initialRuleSnapshotRef.current !== JSON.stringify(rule);
    if (dirty && !window.confirm('Descartar as alterações ainda não salvas?')) return;
    setSearch({ action: undefined });
  };
  const targetSelect = (label: string, key: 'jobFunctionId' | 'activityId' | 'personId', options: Named[]) => <Field label={label}><Select aria-label={label} value={rule[key] ?? ''} onChange={(event) => setRule({ ...rule, [key]: event.target.value || undefined })}><option value="">Todos</option>{options.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>;
  const editorFooter = step === 1 ? <><span className="workflow-modal__progress">Etapa 1 de 4</span><Button type="submit" form="matrix-version-form" loading={save.isPending} trailingIcon={<ChevronRight size={17} />}>Salvar e configurar regras</Button></>
    : step === 2 ? <><Button variant="ghost" onClick={() => setStep(1)} leadingIcon={<ChevronLeft size={17} />}>Voltar</Button><div className="workflow-modal__footer-end"><Button variant="secondary" loading={save.isPending} onClick={() => save.mutate(2)}>Salvar rascunho</Button><Button disabled={!rules.length || rules.some((item) => !item.courseIds.length) || save.isPending} onClick={() => save.mutate(3)} trailingIcon={<ChevronRight size={17} />}>Revisar matriz</Button></div></>
    : step === 3 ? <><Button variant="ghost" onClick={() => setStep(2)} leadingIcon={<ChevronLeft size={17} />}>Voltar às regras</Button><Button onClick={() => setStep(4)} trailingIcon={<ChevronRight size={17} />}>Continuar para publicação</Button></>
    : <><Button variant="ghost" onClick={() => setStep(3)} leadingIcon={<ChevronLeft size={17} />}>Voltar à revisão</Button><Button loading={publish.isPending} onClick={() => publish.mutate()} leadingIcon={<ShieldCheck size={17} />}>Publicar matriz</Button></>;
  return <div className="training-resource matrix-page"><section className="resource-main matrix-overview">
    <div className="matrix-overview-toolbar"><label className="search-field matrix-search"><Search size={18} /><span className="sr-only">Buscar regra</span><Input value={search.q} onChange={(event) => setSearch({ q: event.target.value })} placeholder="Buscar por regra" /></label><Button onClick={begin} leadingIcon={<Plus size={17} />}>{current?.status === 'draft' ? 'Continuar rascunho' : matrixId ? 'Nova versão' : 'Criar matriz'}</Button></div>
    <QueryState loading={matrices.isLoading || detail.isLoading} error={matrices.isError || detail.isError}>
      {current && <header className="matrix-summary"><div className="matrix-summary__identity"><span className="matrix-summary__icon"><Layers3 size={22} /></span><div><div className="matrix-summary__title"><h2>{detail.data?.name}</h2><Badge tone={current.status === 'draft' ? 'warning' : 'success'}>{current.status === 'draft' ? 'Rascunho' : 'Publicada'}</Badge></div><p>Versão {current.versionNo} · Vigência em {formatDateTime(current.effectiveFrom)}</p></div></div><dl className="matrix-summary__facts"><div><dt>Regras</dt><dd>{versionRules(current).length}</dd></div><div><dt>Cursos únicos</dt><dd>{uniqueCourseCount}</dd></div><div><dt>Vínculos</dt><dd>{versionRules(current).reduce((sum, item) => sum + item.courseIds.length, 0)}</dd></div></dl></header>}
      {current && <div className="matrix-list-heading"><div><h3>Regras da matriz</h3><p>{search.q ? `${displayed.length} regras encontradas · ${displayedCourseCount} vínculos` : 'Quem precisa de cada treinamento e em qual condição.'}</p></div></div>}
      <div className="matrix-rule-list">{displayed.map((item, index) => <article className="matrix-rule" key={`${item.name}-${index}`}><div className={`matrix-rule__effect matrix-rule__effect--${item.effect}`} aria-hidden="true">{item.effect === 'require' ? <BookOpenCheck size={21} /> : <ShieldCheck size={21} />}</div><div className="matrix-rule__content"><div className="matrix-rule__heading"><div><h3>{item.name}</h3><p><UsersRound size={15} />{scopeLabel(item)}</p></div><Badge tone={item.effect === 'require' ? 'info' : 'neutral'}>{item.effect === 'require' ? 'Treinamento exigido' : 'Dispensa'}</Badge></div><div className="matrix-rule__courses"><span>Cursos vinculados</span>{item.courseIds.length ? <ul>{item.courseIds.map((id) => <li key={id}>{courses.data?.rows.find((course) => course.id === id)?.name ?? `Curso ${id}`}</li>)}</ul> : <p>Nenhum curso vinculado.</p>}</div></div><span className="matrix-rule__count">{item.courseIds.length}<small>{item.courseIds.length === 1 ? 'curso' : 'cursos'}</small></span></article>)}</div>
      {!current && <div className="matrix-empty"><Layers3 size={30} /><h3>Sua matriz começa pelas regras</h3><p>Crie a primeira versão para relacionar públicos e treinamentos obrigatórios.</p><Button onClick={begin} leadingIcon={<Plus size={17} />}>Criar matriz</Button></div>}
      {current && !displayed.length && <div className="matrix-empty"><Search size={28} /><h3>Nenhuma regra encontrada</h3><p>Tente outro termo ou limpe a busca para visualizar toda a matriz.</p><Button variant="secondary" onClick={() => setSearch({ q: '' })}>Limpar busca</Button></div>}
    </QueryState>
  </section>{search.action === 'new' && <WorkflowModal title={current?.status === 'draft' ? 'Editar rascunho da matriz' : matrixId ? 'Criar nova versão' : 'Criar matriz'} description="Monte a versão com calma. Somente a publicação passa a gerar obrigações." focusKey={step} onClose={closeEditor} footer={editorFooter}>
    <WorkflowStepper steps={['Versão', 'Regras', 'Revisão', 'Publicação']} current={step} onStep={setStep} />
    {step === 1 && <section className="matrix-step matrix-step--version"><div className="matrix-step-intro"><span><CalendarClock size={21} /></span><div><h3>Dados da versão</h3><p>Defina como esta matriz será identificada e quando suas regras entram em vigor.</p></div></div><form id="matrix-version-form" className="form-stack matrix-version-form" onSubmit={(event) => { event.preventDefault(); save.mutate(2); }}><Field label="Nome da matriz"><Input aria-label="Nome da matriz" required maxLength={180} value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="Início da vigência"><Input aria-label="Início da vigência" required type="datetime-local" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} /></Field></form></section>}
    {step === 2 && <div className="matrix-rules-workspace"><section className="matrix-rules-builder">{!showRuleEditor && <div className="matrix-builder-placeholder"><FilePenLine size={26} /><h3>Selecione uma regra para editar</h3><p>Ou comece uma nova regra para definir público, efeito e cursos.</p><Button variant="secondary" onClick={() => { setShowRuleEditor(true); setEditingIndex(null); setRule({ ...emptyRule }); initialRuleSnapshotRef.current = JSON.stringify(emptyRule); setLinkingIndex(null); }} leadingIcon={<Plus size={16} />}>Nova regra</Button></div>}{showRuleEditor && <form className="form-stack" onSubmit={(event) => { event.preventDefault(); if (!rule.name.trim()) return;
      if (editingIndex !== null) { setRules((items) => items.map((item, index) => index === editingIndex ? { ...rule, name: rule.name.trim() } : item)); setLinkingIndex(editingIndex); }
      else { setRules((items) => [...items, { ...rule, name: rule.name.trim() }]); setLinkingIndex(rules.length); }
      setRule({ ...emptyRule }); initialRuleSnapshotRef.current = JSON.stringify(emptyRule); setEditingIndex(null); setShowRuleEditor(false);
    }}><div className="matrix-form-heading"><span><FilePenLine size={19} /></span><div><h3>{editingIndex === null ? 'Criar regra' : 'Editar regra'}</h3><p>Sem filtros, a regra abrange todos da filial.</p></div></div><Field label="Nome da regra"><Input aria-label="Nome da regra" required maxLength={180} value={rule.name} onChange={(event) => setRule({ ...rule, name: event.target.value })} /></Field>
      <Field label="Efeito"><Select aria-label="Efeito da regra" value={rule.effect} onChange={(event) => setRule({ ...rule, effect: event.target.value as Rule['effect'] })}><option value="require">Exigir treinamento</option><option value="waive">Dispensar treinamento</option></Select></Field>
      <Field label={rule.effect === 'waive' ? 'Motivo da dispensa' : 'Descrição (opcional)'}><Textarea aria-label="Descrição da regra" required={rule.effect === 'waive'} maxLength={500} value={rule.reason ?? ''} onChange={(event) => setRule({ ...rule, reason: event.target.value })} /></Field>
      <div className="matrix-form-divider"><span>Escopo da regra</span></div>
      <Field label="Departamento"><Select aria-label="Departamento da regra" value={rule.departmentId ?? ''} onChange={(event) => setRule({ ...rule, departmentId: event.target.value || undefined, sectorId: undefined })}><option value="">Todos</option>{departments.data?.rows.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>
      {rule.departmentId && <Field label="Setor"><Select aria-label="Setor da regra" value={rule.sectorId ?? ''} onChange={(event) => setRule({ ...rule, sectorId: event.target.value || undefined })}><option value="">Todos</option>{sectors.data?.rows.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field>}
      {targetSelect('Cargo', 'jobFunctionId', jobs.data?.rows ?? [])}{targetSelect('Atividade', 'activityId', activities.data?.rows ?? [])}{targetSelect('Colaborador', 'personId', people.data?.rows.map((p) => ({ id: p.id, name: p.fullName })) ?? [])}
      <Button type="submit" variant="secondary" trailingIcon={<ChevronRight size={16} />}>{editingIndex === null ? 'Criar e vincular cursos' : 'Salvar alterações'}</Button>
    </form>}</section><section className="matrix-rules-manager"><header><div><h3>Regras desta versão</h3><p>{rules.length ? `${rules.length} ${rules.length === 1 ? 'regra configurada' : 'regras configuradas'}` : 'Crie a primeira regra para continuar.'}</p></div><Button variant="secondary" size="sm" onClick={() => { setShowRuleEditor(true); setEditingIndex(null); setRule({ ...emptyRule }); initialRuleSnapshotRef.current = JSON.stringify(emptyRule); setLinkingIndex(null); }} leadingIcon={<Plus size={15} />}>Nova regra</Button></header>
    <div className="matrix-draft-rules">{rules.map((item, index) => <article key={index} aria-current={linkingIndex === index ? 'true' : undefined}><button type="button" className="matrix-draft-rule__main" onClick={() => setLinkingIndex(index)}><span className={`matrix-draft-rule__icon matrix-draft-rule__icon--${item.effect}`}>{item.effect === 'require' ? <BookOpenCheck size={17} /> : <ShieldCheck size={17} />}</span><span><strong>{item.name}</strong><small>{scopeLabel(item)} · {item.courseIds.length} {item.courseIds.length === 1 ? 'curso' : 'cursos'}</small></span><ChevronRight size={16} /></button><div className="matrix-draft-rule__actions"><Button variant="ghost" size="icon" aria-label={`Editar ${item.name}`} onClick={() => { setRule({ ...item }); initialRuleSnapshotRef.current = JSON.stringify(item); setEditingIndex(index); setShowRuleEditor(true); setLinkingIndex(null); }}><Pencil size={15} /></Button><Button variant="ghost" size="icon" className="danger" aria-label={`Remover ${item.name}`} onClick={() => { setRules((items) => items.filter((_, i) => i !== index)); setLinkingIndex(null); setEditingIndex(null); setRule({ ...emptyRule }); initialRuleSnapshotRef.current = JSON.stringify(emptyRule); }}><Trash2 size={15} /></Button></div></article>)}</div>
    {linkingIndex !== null && rules[linkingIndex] && <fieldset className="selection-list matrix-course-picker"><legend>Cursos para {rules[linkingIndex]!.name}</legend><p>Selecione todos os cursos desta regra. Evidência é sempre obrigatória; a frequência vem do curso.</p><label className="search-field"><Search size={16} /><span className="sr-only">Buscar curso</span><Input aria-label="Buscar curso para vincular" placeholder="Buscar curso" value={courseSearch} onChange={(event) => setCourseSearch(event.target.value)} /></label>
      <QueryState loading={courses.isLoading} error={courses.isError}>{courses.data?.rows.filter((course) => course.name.toLocaleLowerCase().includes(courseSearch.toLocaleLowerCase())).map((course) => <label key={course.id}><input type="checkbox" checked={rules[linkingIndex]!.courseIds.includes(course.id)} onChange={(event) => setRules((items) => items.map((item, index) => index !== linkingIndex ? item : { ...item, courseIds: event.target.checked ? [...item.courseIds, course.id] : item.courseIds.filter((id) => id !== course.id) }))} /><span>{course.name}<small>{course.validityDays === null ? 'Sem frequência' : `${course.validityDays} dias`} · Evidência obrigatória</small></span></label>)}</QueryState>
      <Button variant="ghost" onClick={() => setLinkingIndex(null)} leadingIcon={<Check size={16} />}>Concluir seleção</Button></fieldset>}
    {!rules.length && <div className="matrix-manager-empty"><CircleDot size={22} /><p>As regras criadas aparecerão aqui para você revisar e vincular cursos.</p></div>}
    {rules.some((item) => !item.courseIds.length) && <p className="matrix-inline-warning">Vincule ao menos um curso a cada regra antes de revisar.</p>}</section></div>}
    {step === 3 && <section className="matrix-step matrix-review"><header><div><h3>Revise antes de publicar</h3><p>Confira o público e os treinamentos de cada regra. A precedência é aplicada automaticamente.</p></div><dl><div><dt>Regras</dt><dd>{rules.length}</dd></div><div><dt>Vínculos</dt><dd>{rules.reduce((sum, item) => sum + item.courseIds.length, 0)}</dd></div></dl></header><div className="matrix-review-list">{rules.map((item, index) => <article key={index}><div><span className={`matrix-rule__effect matrix-rule__effect--${item.effect}`}>{item.effect === 'require' ? <BookOpenCheck size={19} /> : <ShieldCheck size={19} />}</span><div><strong>{item.name}</strong><p>{scopeLabel(item)} · {item.effect === 'require' ? 'Exigir treinamento' : 'Dispensar treinamento'}</p></div></div><ul>{item.courseIds.map((id) => <li key={id}>{courses.data?.rows.find((course) => course.id === id)?.name ?? id}</li>)}</ul></article>)}</div><p className="matrix-review-note"><ShieldCheck size={18} />Toda realização exige evidência. A versão publicada não poderá ser alterada.</p></section>}
    {step === 4 && <section className="matrix-step matrix-publish"><span className="matrix-publish__icon"><ShieldCheck size={28} /></span><div><h3>Pronto para publicar?</h3><p>Ao confirmar, a versão <strong>{name}</strong> entra em vigor em {formatDateTime(effectiveFrom)} e passa a gerar obrigações.</p><ul><li>{rules.length} {rules.length === 1 ? 'regra configurada' : 'regras configuradas'}</li><li>{rules.reduce((sum, item) => sum + item.courseIds.length, 0)} vínculos com cursos</li><li>Versão imutável após publicação</li></ul></div></section>}
  </WorkflowModal>}</div>;
}
