import { useQuery } from '@tanstack/react-query';
import { AlertTriangle, ArrowRight, CalendarRange, RefreshCw } from 'lucide-react';
import { Button, Select } from '../../components/ui/index.js';
import { apiJson } from '../../lib/api.js';
import type { Props, PeriodDays, GroupBy, Envelope, AttentionPage, BreakdownItem, BreakdownEnvelope, HistoryEnvelope, CycleEnvelope } from './types.js';
import { metricRows, seriesValues, seriesLegend, summaryBreakdown, durationLabel } from './format.js';

const copy = {
  people: { title: 'Saúde da estrutura', description: 'Composição da força de trabalho e cadastros que precisam de revisão.' },
  inspections: { title: 'Pulso de ativos e inspeções', description: 'Situação atual do inventário, execução no período e ativos que exigem atenção.' },
  training: { title: 'Cobertura das obrigações', description: 'Obrigações vigentes, conclusões aceitas e vencimentos que pedem intervenção.' },
  apr: { title: 'Fluxo de APR e PT', description: 'Documentos em curso, finalizações do período e impedimentos preventivos.' },
} as const;

export function ModuleAnalytics({ scope, domain, periodDays = 30, groupBy, onPeriodChange, onGroupByChange, onOpenAttention }: Props) {
  const root = `v1/companies/${scope.companyId}/branches/${scope.branchId}/analytics/${domain}`;
  const selectedGroupBy: GroupBy = domain === 'training'
    ? (['course', 'department', 'jobFunction'].includes(String(groupBy)) ? groupBy as GroupBy : 'course')
    : domain === 'apr' ? (['activity', 'status'].includes(String(groupBy)) ? groupBy as GroupBy : 'activity') : 'department';
  const summary = useQuery({ queryKey: ['module-analytics', domain, 'summary', scope], queryFn: () => apiJson<Envelope<unknown>>(`${root}/summary`), staleTime: 60_000 });
  const series = useQuery({ queryKey: ['module-analytics', domain, 'series', scope, periodDays], queryFn: () => apiJson<Envelope<{ items: Array<Record<string, unknown>> }>>(`${root}/series`, { searchParams: { days: periodDays } }), staleTime: 60_000 });
  const attention = useQuery({ queryKey: ['module-analytics', domain, 'attention', scope, periodDays], queryFn: () => apiJson<AttentionPage>(`${root}/attention`, { searchParams: { days: periodDays, page: 1, pageSize: 5 } }), staleTime: 60_000 });
  const detailedBreakdown = useQuery({ queryKey: ['module-analytics', domain, 'breakdown', scope, selectedGroupBy],
    queryFn: () => apiJson<BreakdownEnvelope>(`${root}/breakdown`, { searchParams: { groupBy: selectedGroupBy } }),
    enabled: domain === 'training' || domain === 'apr', staleTime: 60_000 });
  const history = useQuery({ queryKey: ['module-analytics', domain, 'history', scope, periodDays],
    queryFn: () => apiJson<HistoryEnvelope>(`${root}/history`, { searchParams: { days: periodDays } }),
    enabled: domain === 'training' || domain === 'apr', staleTime: 60_000 });
  const cycle = useQuery({ queryKey: ['module-analytics', domain, 'cycle', scope, periodDays],
    queryFn: () => apiJson<CycleEnvelope>(`${root}/cycle`, { searchParams: { days: periodDays } }), enabled: domain === 'apr', staleTime: 60_000 });
  const metrics = metricRows(domain, summary.data?.data);
  const points = seriesValues(domain, series.data?.data);
  const groups = detailedBreakdown.data?.data.items ?? summaryBreakdown(domain, summary.data?.data);
  const historyItems = history.data?.data.items ?? [];
  const historyValues = historyItems.map((item) => domain === 'training' ? item.compliancePercent ?? null
    : item.available ? Number(item.draftAprs ?? 0) + Number(item.draftWorkPermits ?? 0) + Number(item.authorizedWorkPermits ?? 0) : null);
  const seriesAccessibleLabel = points.length
    ? `Atividade factual no período: ${points.map((point) => `${point.label}, ${point.primary} ${seriesLegend[domain][0]}${seriesLegend[domain][1] ? ` e ${point.secondary} ${seriesLegend[domain][1]}` : ''}`).join('; ')}.`
    : 'Atividade factual no período sem pontos disponíveis.';
  const maxPoint = Math.max(1, ...points.flatMap((point) => [point.primary, point.secondary]));
  const groupValue = (item: BreakdownItem) => Number(item.count ?? item.applicable ?? item.registeredAssets ?? 0);
  const maxGroup = Math.max(1, ...groups.map(groupValue));
  const maxHistory = domain === 'training' ? 100 : Math.max(1, ...historyValues.filter((value): value is number => value !== null));
  const missingHistory = historyItems.filter((item) => !item.available);
  const historyAccessibleLabel = historyItems.some((item) => item.available)
    ? `${domain === 'training' ? 'Compliance histórico' : 'Documentos em fluxo historicamente'}: ${historyItems.map((item, index) => item.available ? `${item.date}, ${historyValues[index] ?? 'não aplicável'}${domain === 'training' ? '%' : ''}` : null).filter(Boolean).join('; ')}.${missingHistory.length ? ` Sem snapshot em ${missingHistory.length} datas, de ${missingHistory[0]?.date} a ${missingHistory.at(-1)?.date}.` : ''}`
    : 'Ainda não há snapshots históricos disponíveis para o período.';
  const refresh = () => void Promise.all([summary.refetch(), series.refetch(), attention.refetch(),
    ...(domain === 'training' || domain === 'apr' ? [detailedBreakdown.refetch(), history.refetch()] : []), ...(domain === 'apr' ? [cycle.refetch()] : [])]);
  return <section className="module-analytics" aria-labelledby={`${domain}-analytics-title`}>
    <header className="module-analytics__context"><div><h2 id={`${domain}-analytics-title`}>{copy[domain].title}</h2><p>{copy[domain].description}</p></div><div className="module-analytics__filters"><label><span>Período de atividade</span><Select value={String(periodDays)} onChange={(event) => onPeriodChange(Number(event.target.value) as PeriodDays)}><option value="30">Últimos 30 dias</option><option value="90">Últimos 90 dias</option><option value="180">Últimos 6 meses</option><option value="365">Últimos 12 meses</option></Select></label><Button variant="secondary" size="icon" aria-label="Atualizar painel" loading={summary.isFetching || series.isFetching || attention.isFetching} onClick={refresh}><RefreshCw size={17} /></Button></div></header>
    {summary.isPending ? <div className="module-analytics__skeleton" aria-label="Carregando indicadores"><i /><i /><i /><i /></div> : summary.isError ? <div className="module-analytics__error"><AlertTriangle size={20} /><div><strong>Não foi possível carregar os indicadores atuais.</strong><p>Verifique a conexão e tente novamente.</p></div><Button variant="secondary" size="sm" onClick={() => void summary.refetch()}>Tentar novamente</Button></div> : <div className="module-analytics__metrics">{metrics.map((metric) => <article key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><small>{metric.detail}</small></article>)}</div>}
    <div className="module-analytics__primary">
      <section className="module-analytics__activity"><header><div><h3>Atividade no período</h3><p>Fatos registrados; não altera a leitura do estado atual acima.</p><div className="module-analytics__legend"><span><i />{seriesLegend[domain][0]}</span>{seriesLegend[domain][1] && <span><b />{seriesLegend[domain][1]}</span>}</div></div><span><CalendarRange size={15} /> {periodDays} dias</span></header>{series.isPending ? <div className="module-analytics__pending" role="status">Carregando atividade…</div> : series.isError ? <div className="module-analytics__inline-error"><span>Série indisponível.</span><button onClick={() => void series.refetch()}>Tentar novamente</button></div> : points.some((point) => point.primary || point.secondary) ? <div className="module-analytics__chart" role="img" aria-label={seriesAccessibleLabel}>{points.map((point) => <div key={point.label} aria-hidden="true"><span><i style={{ height: `${Math.max(point.primary ? 6 : 0, point.primary / maxPoint * 100)}%` }} />{point.secondary > 0 && <b style={{ height: `${Math.max(6, point.secondary / maxPoint * 100)}%` }} />}</span><small>{point.label.slice(5)}</small></div>)}</div> : <div className="module-analytics__empty"><strong>Sem atividade no período</strong><p>O estado atual continua disponível; nenhum fato foi registrado neste intervalo.</p></div>}</section>
      <aside className="module-analytics__attention"><header><div><h3>Pontos de atenção</h3><p>Ordenados por impedimento, atraso e incompletude.</p></div><span aria-label={attention.isPending ? 'Quantidade em carregamento' : `${attention.data?.total ?? 0} pontos de atenção`}>{attention.isPending ? '—' : attention.data?.total ?? 0}</span></header>{attention.isPending ? <div className="module-analytics__pending compact" role="status">Carregando pontos de atenção…</div> : attention.isError ? <div className="module-analytics__inline-error"><span>Lista indisponível.</span><button onClick={() => void attention.refetch()}>Tentar novamente</button></div> : attention.data?.items.length ? <div>{attention.data.items.map((item) => <button type="button" key={`${item.kind}:${item.entityId}`} data-severity={item.severity} onClick={() => onOpenAttention?.(item)} disabled={!onOpenAttention}><span><strong>{item.title}</strong><small>{item.detail}</small></span>{onOpenAttention && <ArrowRight size={15} />}</button>)}</div> : <div className="module-analytics__empty compact"><strong>Nenhuma atenção atual</strong><p>Os dados medidos não apontam impedimentos.</p></div>}</aside>
    </div>
    {(domain === 'training' || domain === 'apr') && <section className="module-analytics__history">
      <header><div><h3>Evolução histórica</h3><p>{domain === 'training' ? 'Compliance medido em cada snapshot diário.' : 'Documentos que permaneciam em fluxo em cada data medida.'}</p></div><span>{history.data?.data.availableFrom ? `Desde ${new Date(`${history.data.data.availableFrom}T12:00:00`).toLocaleDateString('pt-BR')}` : 'Histórico iniciado agora'}</span></header>
      {history.isPending ? <div className="module-analytics__pending compact" role="status">Carregando histórico…</div> : history.isError ? <div className="module-analytics__inline-error"><span>Histórico indisponível.</span><button onClick={() => void history.refetch()}>Tentar novamente</button></div> : historyItems.some((item) => item.available) ? <><div className="module-analytics__history-chart" role="img" aria-label={historyAccessibleLabel}>{historyItems.map((item, index) => <i key={item.date} aria-hidden="true" data-missing={!item.available} style={{ height: item.available ? `${Math.max(4, Number(historyValues[index] ?? 0) / maxHistory * 100)}%` : undefined }} />)}</div><div className="module-analytics__history-key"><span><i />Snapshot medido</span>{missingHistory.length > 0 && <span><i data-missing />Sem snapshot</span>}</div></> : <div className="module-analytics__empty compact"><strong>O histórico começa com a projeção atual</strong><p>Datas anteriores não são preenchidas com o valor de hoje.</p></div>}
    </section>}
    {domain === 'apr' && <section className="module-analytics__cycles" aria-label="Tempos medianos de ciclo">
      {cycle.isPending ? <div className="module-analytics__pending compact" role="status">Calculando ciclos…</div> : cycle.isError ? <div className="module-analytics__inline-error"><span>Ciclos indisponíveis.</span><button onClick={() => void cycle.refetch()}>Tentar novamente</button></div> : cycle.data && <><article><span>Finalização da APR</span><strong>{durationLabel(cycle.data.data.aprFinalization.medianHours)}</strong><small>Criação → primeira revisão finalizada · {cycle.data.data.aprFinalization.sampleSize} na amostra</small></article><article><span>Autorização da PT</span><strong>{durationLabel(cycle.data.data.workPermitAuthorization.medianHours)}</strong><small>Criação → autorização · {cycle.data.data.workPermitAuthorization.sampleSize} na amostra</small></article></>}
    </section>}
    <section className="module-analytics__breakdown"><header><div><h3>{domain === 'people' ? 'Composição por departamento' : domain === 'inspections' ? 'Inventário por categoria' : 'Distribuição atual'}</h3><p>Valores absolutos preservam o tamanho real do universo medido.</p></div>{(domain === 'training' || domain === 'apr') && <label className="module-analytics__groupby"><span>Agrupar por</span><Select value={selectedGroupBy} onChange={(event) => onGroupByChange?.(event.target.value as GroupBy)}>{domain === 'training' ? <><option value="course">Curso</option><option value="department">Departamento</option><option value="jobFunction">Cargo</option></> : <><option value="activity">Atividade</option><option value="status">Status</option></>}</Select></label>}</header>{detailedBreakdown.isPending && (domain === 'training' || domain === 'apr') ? <div className="module-analytics__pending compact" role="status">Carregando distribuição…</div> : detailedBreakdown.isError && (domain === 'training' || domain === 'apr') ? <div className="module-analytics__inline-error"><span>Distribuição indisponível.</span><button onClick={() => void detailedBreakdown.refetch()}>Tentar novamente</button></div> : groups.length ? <div>{groups.slice(0, 8).map((item) => { const value = groupValue(item); return <article key={item.id}><span><strong>{item.label}</strong><small>{value.toLocaleString('pt-BR')}{item.compliancePercent !== undefined ? ` · ${item.compliancePercent === null ? 'não aplicável' : `${item.compliancePercent.toLocaleString('pt-BR', { maximumFractionDigits: 1 })}%`}` : ''}</small></span><i><b style={{ width: `${value / maxGroup * 100}%` }} /></i></article>; })}</div> : <div className="module-analytics__empty compact"><strong>Sem distribuição disponível</strong><p>Cadastre o universo inicial para visualizar os recortes.</p></div>}</section>
    {summary.data && <footer>Data de referência: {new Date(`${summary.data.asOf}T12:00:00`).toLocaleDateString('pt-BR')} · Atualizado em {new Date(summary.data.generatedAt).toLocaleString('pt-BR')}</footer>}
  </section>;
}
