export const siteUrl = 'https://nexasst.com.br';
export const siteTitle = 'Gestão de treinamentos e inspeções de SST | NexaSST';
export const siteDescription = 'Organize treinamentos de segurança do trabalho, inspeções de extintores, APR e evidências com o NexaSST. Agende uma demonstração.';
export const demoUrl = 'https://wa.me/5542998366677?text=Ol%C3%A1%2C%20gostaria%20de%20agendar%20uma%20demonstra%C3%A7%C3%A3o%20do%20NexaSST.';
const nrBase = 'https://www.gov.br/trabalho-e-emprego/pt-br/acesso-a-informacao/participacao-social/conselhos-e-orgaos-colegiados/comissao-tripartite-partitaria-permanente/normas-regulamentadora/normas-regulamentadoras-vigentes/';
export const sources = {
  cbo: 'https://www.gov.br/trabalho-e-emprego/pt-br/assuntos/cbo/servicos/downloads/livro-1-portal-cbo.pdf',
  nr17: `${nrBase}norma-regulamentadora-no-17-nr-17`,
  nr33: `${nrBase}norma-regulamentadora-no-33-nr-33`,
};
export const searchQuestions = [
  ['Como fazer a gestão de treinamentos com o NexaSST?', 'Cadastre os colaboradores, cargos e cursos, defina as matrizes de capacitação e organize as turmas. Depois, registre as presenças e acompanhe os vencimentos por colaborador. O NexaSST conecta essas informações para ajudar sua equipe a identificar pendências e planejar os próximos treinamentos de segurança do trabalho.'],
  ['Como fazer inspeções com o NexaSST?', 'Cadastre os equipamentos e ativos, configure os checklists da operação e use o aplicativo para registrar a inspeção no campo, com fotos e observações. Consulte o histórico de cada ativo e acompanhe os planos de ação para os desvios identificados. Esse fluxo pode ser usado em inspeções de extintores e outros equipamentos, conforme o checklist definido pela equipe.'],
  ['Como fazer APR ou PT com o NexaSST?', 'Para a Análise Preliminar de Riscos (APR), cadastre a atividade, selecione o modelo e preencha a análise conforme as condições reais da tarefa. Para a Permissão de Trabalho (PT), organize o registro e siga o fluxo de autorização pelos responsáveis. O NexaSST reúne documentos e relatórios para consulta e acompanhamento; a análise e a autorização continuam com a equipe responsável.'],
  ['O que é CBO e para que serve no NexaSST?', 'CBO é a Classificação Brasileira de Ocupações, que identifica as ocupações por código. No NexaSST, o CBO é um campo opcional no cadastro de cargos e ajuda a identificar a ocupação associada à função do colaborador. Por exemplo, o código do Técnico em segurança no trabalho é 3516-05. Os treinamentos necessários são definidos nas matrizes de capacitação, conforme a função e a atividade.'],
  ['O que é inventário de espaços confinados?', 'É o conjunto organizado de registros que identifica os espaços confinados da operação e reúne informações sobre cada um deles. No NexaSST, você pode cadastrar os espaços, organizar planos de resgate e responsáveis técnicos e disponibilizar informações por QR Code, conforme as permissões de acesso. Manter esse inventário atualizado facilita a consulta pela equipe; o cadastro não autoriza, por si só, a entrada ou o trabalho no espaço.'],
] as const;

export interface Guide { slug: string; title: string; description: string; answer: string; sections: ReadonlyArray<readonly [string, string]>; checklist: string[]; source?: readonly [string, string]; faq?: readonly [string, string]; steps?: string[] }
export const guides: Guide[] = [
  {
    slug: 'gestao-de-treinamentos-seguranca-do-trabalho', title: 'Gestão de treinamentos de segurança do trabalho com o NexaSST',
    description: 'Veja como cadastrar cursos, organizar turmas e matrizes e acompanhar presenças e vencimentos de treinamentos no NexaSST.',
    answer: 'Para melhorar a gestão de treinamento em segurança do trabalho, conecte a exigência da função ao curso realizado, à presença e ao vencimento de cada colaborador. Essa visão mostra quem precisa de capacitação e quais registros precisam ser conferidos.',
    sections: [
      ['Comece pela matriz de capacitação', 'Liste as funções e atividades e peça à equipe técnica que defina os treinamentos aplicáveis. Uma matriz deve representar a operação real: mudanças de função e de atividade precisam entrar na revisão. Não use a mesma lista para todos apenas por conveniência.'],
      ['Separe conclusão, evidência e validade', 'Uma inscrição em turma não comprova conclusão. Relacione o evento, a participação e a evidência correspondente ao colaborador. Organize as datas e regras de validade conforme o treinamento e sua aplicação, sem presumir um prazo universal para todas as NRs.'],
      ['Da turma ao acompanhamento no NexaSST', 'Depois de organizar os cadastros e a matriz, reúna os participantes em turmas e registre as presenças. Consulte os vencimentos para planejar a próxima capacitação e confira o registro do colaborador antes de decidir que ele está apto para uma atividade. A matriz deve refletir os critérios definidos pela sua equipe; o sistema não escolhe automaticamente todos os treinamentos exigidos por uma ocupação.'],
    ], faq: searchQuestions[0], steps: ['Cadastre cargos e colaboradores na estrutura de pessoas da empresa.', 'Cadastre os cursos e confira a frequência e as regras de validade aplicáveis.', 'Defina as matrizes de capacitação conforme as funções e atividades.', 'Organize as turmas e seus participantes e registre as presenças.', 'Consulte os vencimentos por colaborador para planejar as próximas turmas.'], checklist: ['Mapear funções e atividades com a equipe de SST.', 'Conferir participantes e registros de cada turma.', 'Priorizar capacitações pendentes e próximas do vencimento.', 'Revisar a matriz quando a operação mudar.'],
  },
  {
    slug: 'inspecao-online-extintores', title: 'Inspeção online de extintores e equipamentos com o NexaSST',
    description: 'Aprenda a organizar ativos e checklists e registrar inspeções de extintores e equipamentos com fotos, histórico e planos de ação no NexaSST.',
    answer: 'Inspeção online de extintor é a organização digital do registro de uma verificação feita no local. Ela conecta a identificação do equipamento ao checklist, às fotos e às ações necessárias, sem substituir a inspeção física ou a manutenção.',
    sections: [
      ['Identifique cada ativo antes de inspecionar', 'Cadastre uma identificação única e a localização do equipamento. Se houver vários extintores próximos, confirme que o registro corresponde ao ativo inspecionado. Um QR Code pode facilitar a consulta e diminuir a confusão entre equipamentos.'],
      ['Transforme o desvio em acompanhamento', 'Use um checklist definido pela equipe responsável e registre a condição observada. Quando houver desvio, relacione a evidência ao ativo e à ação necessária. A periodicidade e os critérios técnicos devem ser definidos conforme o equipamento e as exigências aplicáveis; este guia não é um checklist técnico de aprovação.'],
      ['Do checklist ao plano de ação no NexaSST', 'No módulo de inspeções, organize as categorias e tipos de equipamento, cadastre os ativos e publique o checklist que a equipe utilizará. O aplicativo permite registrar a inspeção no campo. Depois do registro, consulte o histórico do ativo e acompanhe os planos de ação. Hidrantes, mangueiras e outros equipamentos podem usar esse fluxo conforme a configuração da operação e seus critérios técnicos.'],
    ], faq: searchQuestions[1], steps: ['Organize as categorias e os tipos de equipamento que serão inspecionados.', 'Cadastre cada ativo com sua identificação e localização.', 'Configure e publique o checklist adequado à operação, conforme as permissões.', 'No aplicativo, selecione o ativo e registre respostas, observações e fotos no campo.', 'Confira a confirmação da sincronização e consulte o histórico e os planos de ação.'], checklist: ['Conferir identificação e localização do ativo.', 'Usar o checklist técnico aprovado para o equipamento.', 'Registrar fotos e condição observada no campo.', 'Acompanhar desvios e revisar o histórico do ativo.'],
  },
  {
    slug: 'apr-seguranca-do-trabalho', title: 'Como fazer APR e Permissão de Trabalho com o NexaSST',
    description: 'Veja como organizar atividades, modelos e registros de APR e PT no NexaSST, com análise de riscos e autorização pelos responsáveis.',
    answer: 'APR é a Análise Preliminar de Riscos de uma atividade. Seu registro ajuda a explicitar os riscos identificados e as medidas preventivas a avaliar antes do trabalho, com contexto suficiente para a equipe responsável revisar a tarefa.',
    sections: [
      ['Descreva a tarefa real', 'Registre a atividade, o local e as condições de execução. Um modelo pode servir como ponto de partida, mas precisa ser revisado quando as condições mudam. Copiar uma APR sem conferir o contexto pode deixar riscos relevantes fora da análise.'],
      ['Distinga análise e autorização', 'A APR registra a análise; a Permissão de Trabalho organiza a autorização quando aplicável. A existência de um documento não comprova, sozinha, que todas as medidas foram executadas ou que a tarefa pode começar. As decisões cabem aos responsáveis da operação.'],
      ['Organização digital no NexaSST', 'O NexaSST oferece registros de APR, atividades, modelos, relatórios e permissões de trabalho. Compare o fluxo de revisão e consulta com sua rotina atual. A trava preventiva antes da tarefa é uma oferta sob projeto e orçamento, conforme a proposta comercial.'],
    ], faq: searchQuestions[2], steps: ['Cadastre a atividade e selecione o modelo de APR aplicável.', 'Preencha o registro considerando o local e as condições reais da tarefa.', 'Revise os riscos, as medidas preventivas e os responsáveis antes da finalização.', 'Quando houver PT, preencha a permissão e encaminhe pelo fluxo de autorização da operação.', 'Consulte os documentos e relatórios para acompanhar o que foi registrado e autorizado.'], checklist: ['Identificar atividade, local e condições reais.', 'Revisar riscos e medidas com a equipe responsável.', 'Conferir a autorização de trabalho quando aplicável.', 'Preservar o registro e sua relação com a atividade.'],
  },
  {
    slug: 'cbo-tecnico-seguranca-do-trabalho', title: 'CBO do técnico de segurança do trabalho: 3516-05',
    description: 'Consulte o CBO 3516-05 do técnico de segurança do trabalho e entenda como informar esse código no cadastro de cargos do NexaSST.',
    answer: 'O CBO do Técnico em segurança no trabalho é 3516-05. A referência é a Classificação Brasileira de Ocupações, disponibilizada pelo Ministério do Trabalho e Emprego (MTE).',
    sections: [
      ['Onde conferir o código', 'Consulte a família 3516 na publicação oficial da CBO do MTE, vinculada abaixo. Para preencher registros administrativos, confira a ocupação e a informação exigida pelo processo correspondente. O código ocupacional não comprova capacitação de uma pessoa nem certifica um sistema de SST.'],
      ['Da consulta do CBO à rotina de SST', 'Quem procura o CBO pode também precisar organizar as atividades do profissional na empresa. Separe a consulta cadastral da gestão operacional: acompanhe treinamentos, inspeções, APRs e evidências com seus responsáveis e prazos.'],
      ['Para que serve o CBO no cadastro de cargos', 'No NexaSST, cada cargo pode receber um CBO opcional. O código identifica a ocupação associada ao cargo, enquanto o vínculo do colaborador à sua função ajuda a organizar a estrutura de pessoas. O CBO não gera uma matriz de treinamentos automaticamente: a equipe define as capacitações conforme as funções e as atividades da operação.'],
    ], faq: searchQuestions[3], steps: ['Confira na fonte oficial o CBO que corresponde à ocupação.', 'Abra o cadastro de cargos e crie ou edite o cargo correspondente.', 'Informe o nome do cargo e, se aplicável, seu CBO no campo opcional.', 'Relacione o cargo ao colaborador no cadastro de pessoas.', 'Defina as matrizes de capacitação conforme as funções e atividades, sem usar o código como comprovação de treinamento.'], checklist: ['Conferir o código na fonte oficial.', 'Distinguir ocupação de comprovação de qualificação.', 'Mapear as rotinas que precisam de acompanhamento.', 'Avaliar o software com exemplos da sua operação.'], source: ['CBO oficial — família 3516', sources.cbo],
  },
  {
    slug: 'espaco-confinado-inventario', title: 'Inventário de espaços confinados: o que é e como organizar',
    description: 'Entenda o inventário de espaços confinados e veja como organizar cadastros, planos de resgate, responsáveis e QR Code no NexaSST.',
    answer: 'Inventário de espaços confinados é o conjunto de registros que identifica os espaços da operação e organiza as informações sobre cada um deles. No NexaSST, esse trabalho reúne o cadastro dos espaços, planos de resgate, responsáveis técnicos e publicação por QR Code, conforme as permissões.',
    sections: [
      ['Mantenha o inventário consultável', 'Diferencie cada espaço por identificação e localização e revise as informações quando houver mudanças. Um registro útil permite que a equipe encontre o espaço correto e consulte o contexto atualizado, sem depender apenas da memória de quem conhece a instalação.'],
      ['Não confunda inventário com autorização de entrada', 'O cadastro de um espaço não autoriza entrada ou trabalho. Os procedimentos e requisitos aplicáveis precisam ser avaliados pela equipe responsável à luz da NR-33 vigente. Consulte a fonte oficial abaixo; este conteúdo trata da organização de registros.'],
      ['Inventário no NexaSST', 'O NexaSST possui um módulo de inventário de espaços confinados com cadastro de espaços, planos de resgate, responsáveis técnicos e publicação por QR Code, conforme permissões. Avalie esse fluxo na demonstração e confirme o escopo contratado para sua operação.'],
    ], faq: searchQuestions[4], steps: ['Identifique os espaços da operação com a equipe técnica.', 'Cadastre cada espaço no módulo de inventário, com sua identificação e localização.', 'Organize os planos de resgate e responsáveis técnicos correspondentes.', 'Revise as informações antes da publicação e disponibilize o QR Code conforme as permissões.', 'Mantenha os registros atualizados quando houver mudanças na operação.'], checklist: ['Identificar cada espaço e sua localização.', 'Manter responsáveis e documentos consultáveis.', 'Revisar registros quando as condições mudarem.', 'Consultar a NR-33 com os responsáveis técnicos.'], source: ['NR-33 — fonte oficial do MTE', sources.nr33],
  },
  {
    slug: 'ergonomia-aep-aet', title: 'Ergonomia no trabalho: organização de AEP, AET e ações',
    description: 'Entenda como organizar avaliações e ações de ergonomia, consultar a NR-17 e definir o escopo de uma solução para a sua equipe.',
    answer: 'A organização da ergonomia no trabalho começa por relacionar os registros de avaliação às situações de trabalho e às ações propostas. Consulte a NR-17 para avaliar, com os responsáveis técnicos, os requisitos de Avaliação Ergonômica Preliminar (AEP) e Análise Ergonômica do Trabalho (AET) aplicáveis.',
    sections: [
      ['Organize o contexto da avaliação', 'Associe os registros à atividade e ao local avaliados. Preserve o contexto observado e a identificação do responsável. Um documento isolado fica mais difícil de acompanhar quando a equipe não consegue relacioná-lo à situação de trabalho que motivou a avaliação.'],
      ['Acompanhe as ações depois do documento', 'Defina quem acompanha as ações propostas e mantenha as evidências de execução consultáveis. A decisão sobre a avaliação necessária e sua metodologia exige análise técnica; a ferramenta de gestão não substitui esse trabalho.'],
      ['Confirme o escopo antes de contratar', 'A oferta comercial do NexaSST apresenta ergonomia, AEP e AET. Confirme em demonstração os recursos disponíveis, a implantação e o escopo da proposta antes de escolher um plano. Este guia não presume emissão automática de laudos nem atendimento integral à NR-17.'],
    ], steps: ['Identifique as situações de trabalho que precisam de avaliação.', 'Defina com a equipe técnica a avaliação e os registros aplicáveis.', 'Organize os documentos por atividade, local e responsável.', 'Acompanhe as ações propostas e suas evidências de execução.', 'Confirme em demonstração o escopo de ergonomia disponível na proposta do NexaSST.'], checklist: ['Identificar atividade e situação de trabalho.', 'Consultar a NR-17 vigente com a equipe técnica.', 'Relacionar avaliações às ações e responsáveis.', 'Confirmar recursos de ergonomia na demonstração.'], source: ['NR-17 — fonte oficial do MTE', sources.nr17],
  },
];
