import { MarketingHeader } from '../features/landing/MarketingHeader.js';
import { renderToStaticMarkup } from 'react-dom/server';
import { LandingPageV0 } from '../pages/LandingPageV0.js';
import { demoUrl, guides, siteDescription, siteTitle, siteUrl } from './content.js';
import type { Guide } from './content.js';
export { guides, siteDescription, siteTitle, siteUrl };
export const renderHome = () => renderToStaticMarkup(<LandingPageV0 />);
export function renderGuide(guide: Guide) {
  const url = `${siteUrl}/guias/${guide.slug}/`;
  return renderToStaticMarkup(<div className={String.raw`landing-v0 [--landing-navy:#09264a] [--landing-navy-strong:#06172f] [--landing-emerald:#087a58] [--landing-emerald-bright:#0c936c] [--landing-field:#f8f9f7] [--landing-white:#fff] [--landing-ink:#10243e] [--landing-muted:#3d536b] [--landing-line:#cad6df] [min-width:20rem] min-h-screen overflow-x-clip text-(--landing-ink) [background:var(--landing-field)] font-['Manrope_Variable',Manrope,sans-serif] **:box-border [&_*::before]:box-border [&_*::after]:box-border [&_h1]:m-0 [&_h1]:text-balance [&_h2]:m-0 [&_h2]:text-balance [&_h3]:m-0 [&_h3]:text-balance [&_p]:m-0 [&_p]:text-pretty [&_a]:text-inherit motion-reduce:**:scroll-auto! motion-reduce:**:duration-[0ms]! motion-reduce:**:[animation-duration:0ms]! motion-reduce:[&_*::before]:scroll-auto! motion-reduce:[&_*::before]:duration-[0ms]! motion-reduce:[&_*::before]:[animation-duration:0ms]! motion-reduce:[&_*::after]:scroll-auto! motion-reduce:[&_*::after]:duration-[0ms]! motion-reduce:[&_*::after]:[animation-duration:0ms]! [&:has(.legal-article)_.landing-v0\_\_header]:relative [&:has(.legal-article)_.landing-v0\_\_header]:top-auto [&:has(.legal-article)_.landing-v0\_\_header]:mt-[24px] [&:has(.legal-article)_.landing-v0\_\_header]:grid-cols-[1fr_auto] [&:has(.legal-article)_.landing-v0\_\_header_nav]:flex [&:has(.legal-article)_.landing-v0\_\_header_nav]:items-center [&:has(.legal-article)_.landing-v0\_\_header_nav]:gap-[20px] [&:has(.legal-article)_.legal-article]:pt-[40px] max-[620px]:[&:has(.legal-article)_.landing-v0\_\_header]:rounded-[20px] max-[620px]:[&:has(.legal-article)_.landing-v0\_\_header_nav]:gap-[10px] max-[620px]:[&:has(.legal-article)_.landing-v0\_\_header_nav_a]:text-[12px]`}><MarketingHeader />
    <main className={String.raw`search-article [&_a:not(.landing-v0\_\_cta)]:text-(--landing-emerald) [&_a:not(.landing-v0\_\_cta)]:underline [&_a:not(.landing-v0\_\_cta)]:underline-offset-4 w-[min(calc(100%-40px),860px)] m-[0_auto] p-[56px_0_96px] text-(--landing-navy-strong) [&_h1]:m-[32px_0_24px] [&_h1]:text-[clamp(32px,5vw,52px)] [&_h1]:leading-[1.12] [&_h1]:tracking-tight [&_h2]:m-[36px_0_16px] [&_h2]:text-[26px] [&_h2]:leading-[1.3] [&_p]:text-[18px] [&_p]:leading-[1.75] [&_li]:text-[18px] [&_li]:leading-[1.75] [&_ul]:pl-[24px] [&_ul]:[list-style:disc] [&_.search-answer]:text-[21px] [&_.landing-v0\_\_cta]:inline-flex [&_.landing-v0\_\_cta]:mt-[24px] [&_ol]:pl-[24px] [&_ol]:[list-style:decimal]`}><nav aria-label="Caminho da página"><a href="/">Início</a> / <a href="/#guias">Guias</a></nav>
      <article><h1>{guide.title}</h1><p className={"search-answer"}>{guide.answer}</p>{guide.sections.map(([title, text]) => <section key={title}><h2>{title}</h2><p>{text}</p></section>)}
        {guide.faq && <section><h2>{guide.faq[0]}</h2><p>{guide.faq[1]}</p></section>}
        {guide.steps && <section><h2>Passo a passo para organizar os registros</h2><ol>{guide.steps.map((step) => <li key={step}>{step}</li>)}</ol></section>}
        <h2>Roteiro para organizar a rotina</h2><ul>{guide.checklist.map((item) => <li key={item}>{item}</li>)}</ul>
        {guide.source && <p>Referência: <a href={guide.source[1]}>{guide.source[0]}</a>.</p>}
        <p>Por Matheus Padilha Rodrigues · <a href="/sobre/">Sobre o autor e o NexaSST</a> · Atualizado em 27/09/2026.</p>
        <a className={"landing-v0__cta inline-flex min-h-[44px] items-center justify-center p-[8px_16px] text-white! border-0 rounded-[12px] [background:var(--landing-emerald)] font-[inherit] text-[16px] font-[650] no-underline cursor-pointer shadow-[0_10px_26px_rgb(8_122_88/24%)] [transition:background-color_140ms_cubic-bezier(.23,1,.32,1),transform_140ms_cubic-bezier(.23,1,.32,1),box-shadow_140ms_cubic-bezier(.23,1,.32,1)] [&:hover]:bg-[#076348] [&:hover]:shadow-[0_14px_30px_rgb(8_122_88/30%)] active:transform-[scale(.97)] focus-visible:[outline:3px_solid_#6ee7b7] focus-visible:outline-offset-[3px]"} href={demoUrl}>Agendar demonstração</a>
      </article>
      <aside><h2>Continue a leitura</h2><ul>{guides.filter((item) => item.slug !== guide.slug).map((item) => <li key={item.slug}><a href={`/guias/${item.slug}/`}>{item.title}</a></li>)}</ul><a href={`${url}index.md`}>Ler em Markdown</a></aside>
    </main>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@graph': [
      { '@type': 'Article', headline: guide.title, description: guide.description, url, inLanguage: 'pt-BR', dateModified: '2026-09-27', author: { '@type': 'Person', '@id': `${siteUrl}/sobre/#matheus`, name: 'Matheus Padilha Rodrigues', url: `${siteUrl}/sobre/` }, publisher: { '@type': 'Organization', name: 'NexaSST', url: siteUrl } },
      ...(guide.faq ? [{ '@type': 'FAQPage', mainEntity: [{ '@type': 'Question', name: guide.faq[0], acceptedAnswer: { '@type': 'Answer', text: guide.faq[1] } }] }] : []),
      { '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'NexaSST', item: `${siteUrl}/` }, { '@type': 'ListItem', position: 2, name: guide.title, item: url }] },
    ] }).replace(/</g, '\\u003c') }} />
  </div>);
}
export function guideMarkdown(guide: Guide) {
  return `# ${guide.title}\n\nURL canônica: ${siteUrl}/guias/${guide.slug}/\n\n${guide.answer}\n\n${guide.sections.map(([title, text]) => `## ${title}\n\n${text}`).join('\n\n')}${guide.faq ? `\n\n## ${guide.faq[0]}\n\n${guide.faq[1]}` : ''}${guide.steps ? `\n\n## Passo a passo para organizar os registros\n\n${guide.steps.map((step, index) => `${index + 1}. ${step}`).join('\n')}` : ''}\n\n## Roteiro para organizar a rotina\n\n${guide.checklist.map((item) => `- ${item}`).join('\n')}${guide.source ? `\n\nReferência: [${guide.source[0]}](${guide.source[1]})` : ''}\n\nAutor: Matheus Padilha Rodrigues. Sobre o autor: ${siteUrl}/sobre/. Atualizado em 27/09/2026.\n\n[Demonstração](${demoUrl})\n\n## Continue a leitura\n\n${guides.filter((item) => item.slug !== guide.slug).map((item) => `- [${item.title}](${siteUrl}/guias/${item.slug}/)`).join('\n')}\n`;
}
export const markdownIntro = `# NexaSST — gestão de segurança do trabalho\n\nURL canônica: ${siteUrl}/\n\n${siteDescription}\n\nPúblico: profissionais e equipes de SST de empresas brasileiras.\n\n`;
