import { guides, searchQuestions, siteDescription, siteTitle, siteUrl, sources } from './content.js';

export function SearchContent() {
  return <>
    <section className={"landing-v0__faq w-[min(calc(100%-48px),1280px)] m-[0_auto] p-[96px_0] grid grid-cols-12 gap-[64px_24px] border-t border-solid border-t-[var(--landing-line)] [&_h2]:mt-[16px] [&_h2]:text-(--landing-navy-strong) [&_h2]:text-[48px] [&_h2]:font-[650] [&_h2]:leading-none [&_h2]:tracking-[-.035em] [&_>_div:first-child]:col-[1/6] [&_>_div:last-child]:col-[7/13] [&_details]:border-t [&_details]:border-solid [&_details]:border-t-[var(--landing-line)] [&_details:last-child]:border-b [&_details:last-child]:border-solid [&_details:last-child]:border-b-[var(--landing-line)] [&_summary]:p-[24px_32px_24px_0] [&_summary]:text-(--landing-navy-strong) [&_summary]:text-[18px] [&_summary]:font-[650] [&_summary]:leading-[28px] [&_summary]:cursor-pointer [&_details_p]:max-w-[58ch] [&_details_p]:p-[0_0_24px] [&_details_p]:text-(--landing-muted) [&_details_p]:text-[16px] [&_details_p]:leading-[24px] max-[900px]:w-[min(calc(100%-32px),1280px)] max-[900px]:p-[80px_0] max-[900px]:grid-cols-[1fr] max-[900px]:gap-[48px] max-[900px]:[&_>_div:first-child]:col-1 max-[900px]:[&_>_div:last-child]:col-1 max-[560px]:[&_h2]:text-[36px] max-[560px]:[&_h2]:leading-[40px]"} id="guias" aria-labelledby="guides-title">
      <div><span className={"landing-v0__eyebrow block text-(--landing-emerald) text-[12px] font-[650] leading-[16px] tracking-[.08em] uppercase"}>Guias de segurança do trabalho</span><h2 id="guides-title">Organize a rotina antes de escolher a ferramenta.</h2></div>
      <div className={"search-guides [&_article]:p-[24px_0] [&_article]:border-t [&_article]:border-solid [&_article]:border-t-[var(--landing-line)] [&_h3]:text-[20px] [&_h3]:leading-[1.4] [&_p]:mt-[12px] [&_p]:text-(--landing-muted) [&_p]:leading-[1.6] [&_a]:text-(--landing-emerald)! [&_a]:underline [&_a]:underline-offset-4"}>{guides.map((guide) => <article key={guide.slug}><h3><a href={`/guias/${guide.slug}/`}>{guide.title}</a></h3><p>{guide.description}</p></article>)}</div>
    </section>
    <section className={"landing-v0__faq w-[min(calc(100%-48px),1280px)] m-[0_auto] p-[96px_0] grid grid-cols-12 gap-[64px_24px] border-t border-solid border-t-[var(--landing-line)] [&_h2]:mt-[16px] [&_h2]:text-(--landing-navy-strong) [&_h2]:text-[48px] [&_h2]:font-[650] [&_h2]:leading-none [&_h2]:tracking-[-.035em] [&_>_div:first-child]:col-[1/6] [&_>_div:last-child]:col-[7/13] [&_details]:border-t [&_details]:border-solid [&_details]:border-t-[var(--landing-line)] [&_details:last-child]:border-b [&_details:last-child]:border-solid [&_details:last-child]:border-b-[var(--landing-line)] [&_summary]:p-[24px_32px_24px_0] [&_summary]:text-(--landing-navy-strong) [&_summary]:text-[18px] [&_summary]:font-[650] [&_summary]:leading-[28px] [&_summary]:cursor-pointer [&_details_p]:max-w-[58ch] [&_details_p]:p-[0_0_24px] [&_details_p]:text-(--landing-muted) [&_details_p]:text-[16px] [&_details_p]:leading-[24px] max-[900px]:w-[min(calc(100%-32px),1280px)] max-[900px]:p-[80px_0] max-[900px]:grid-cols-[1fr] max-[900px]:gap-[48px] max-[900px]:[&_>_div:first-child]:col-1 max-[900px]:[&_>_div:last-child]:col-1 max-[560px]:[&_h2]:text-[36px] max-[560px]:[&_h2]:leading-[40px]"} aria-labelledby="search-title">
      <div><span className={"landing-v0__eyebrow block text-(--landing-emerald) text-[12px] font-[650] leading-[16px] tracking-[.08em] uppercase"}>Dúvidas sobre a rotina de SST</span><h2 id="search-title">Treinamentos, inspeções e riscos: por onde começar?</h2></div>
      <div>{searchQuestions.map(([question, answer]) => {
        const guide = guides.find((item) => item.faq?.[0] === question);
        return <details key={question}><summary>{question}</summary><p>{answer}</p>{guide && <p><a href={`/guias/${guide.slug}/`}>Veja o guia completo</a></p>}</details>;
      })}
        <p className={"search-sources mt-[12px] text-(--landing-muted) leading-[1.6] [&_a]:text-(--landing-emerald)! [&_a]:underline [&_a]:underline-offset-4"}>Fontes oficiais: <a href={sources.cbo}>CBO do MTE</a>, <a href={sources.nr17}>NR-17</a> e <a href={sources.nr33}>NR-33</a>.</p>
      </div>
    </section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context': 'https://schema.org', '@graph': [
      { '@type': 'Organization', '@id': `${siteUrl}/#organization`, name: 'NexaSST', url: siteUrl, logo: `${siteUrl}/brand/nexasst-symbol-flat.png`, description: siteDescription },
      { '@type': 'WebSite', '@id': `${siteUrl}/#website`, name: 'NexaSST', url: siteUrl, inLanguage: 'pt-BR', publisher: { '@id': `${siteUrl}/#organization` } },
      { '@type': 'WebPage', '@id': `${siteUrl}/#webpage`, url: `${siteUrl}/`, name: siteTitle, description: siteDescription, inLanguage: 'pt-BR', isPartOf: { '@id': `${siteUrl}/#website` } },
      { '@type': 'FAQPage', mainEntity: searchQuestions.map(([name, text]) => ({ '@type': 'Question', name, acceptedAnswer: { '@type': 'Answer', text } })) },
    ] }).replace(/</g, '\\u003c') }} />
  </>;
}
